export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number; // 0-basiert
  explanation: string;
}

export const QUIZZES: Record<string, QuizQuestion[]> = {
  "M01": [
    {
      id: "M01-Q1",
      question: "Was schreibt § 267 HGB für eine 'kleine' GmbH bezüglich der Offenlegungspflicht vor?",
      options: [
        "A) Vollständiger Jahresabschluss inklusive Lagebericht",
        "B) Bilanz, GuV und Anhang",
        "C) Nur verkürzte Bilanz, keine GuV",
        "D) Keine Offenlegungspflicht",
      ],
      correctIndex: 2,
      explanation: "Kleine GmbHs (Bilanzsumme ≤ 6 Mio. EUR, Umsatz ≤ 12 Mio. EUR, ≤ 50 MA) müssen laut § 267 HGB nur eine verkürzte Bilanz ohne GuV offenlegen. Für den Kreditgeber bedeutet das: GuV-Daten müssen im Rahmen der § 18 KWG-Prüfung direkt beim Kunden angefordert werden.",
    },
    {
      id: "M01-Q2",
      question: "Was besagt die 'Goldene Bilanzregel' im Kontext der Kreditanalyse?",
      options: [
        "A) Das Eigenkapital muss mindestens 30 % der Bilanzsumme betragen",
        "B) Langfristig gebundenes Vermögen sollte durch langfristiges Kapital finanziert sein",
        "C) Der Jahresüberschuss muss stets größer als die Zinslast sein",
        "D) Anlagevermögen darf nicht durch kurzfristige Bankdarlehen finanziert werden, sofern der Zinssatz unter 5 % liegt",
      ],
      correctIndex: 1,
      explanation: "Die Goldene Bilanzregel (Fristenkongruenz) fordert, dass langfristig gebundenes Vermögen (z. B. Maschinen) durch langfristiges Kapital finanziert wird. Eine Verletzung — kurzfristige Darlehen zur Maschinenfinanzierung — ist ein strukturelles Warnsignal für den Kreditgeber.",
    },
    {
      id: "M01-Q3",
      question: "Ab welcher Kredithöhe verpflichtet § 18 KWG ein Kreditinstitut dazu, sich die wirtschaftlichen Verhältnisse des Kreditnehmers offenbaren zu lassen?",
      options: [
        "A) Ab 250.000 EUR",
        "B) Ab 500.000 EUR",
        "C) Ab 750.000 EUR",
        "D) Ab 1.000.000 EUR",
      ],
      correctIndex: 2,
      explanation: "§ 18 KWG verpflichtet Kreditinstitute bei Krediten ab 750.000 EUR, sich die wirtschaftlichen Verhältnisse des Kreditnehmers (insbesondere den Jahresabschluss) offenbaren zu lassen. Verweigert der Kunde die Vorlage, ist dies selbst ein Warnsignal und begründet eine Handlungspflicht der Bank.",
    },
    {
      id: "M01-Q4",
      question: "Ein Unternehmen hat Eigenkapital von 800.000 EUR und eine Bilanzsumme von 4.000.000 EUR. Wie hoch ist die Eigenkapitalquote, und wie ist sie branchentypisch einzuordnen?",
      options: [
        "A) 20 % – für viele KMU bereits ein solider Wert",
        "B) 25 % – im deutschen Mittelstand der Standardwert",
        "C) 20 % – kritisch, da der Richtwert bei mindestens 30 % liegt",
        "D) 5 % – viel zu niedrig für jede Branche",
      ],
      correctIndex: 0,
      explanation: "EK-Quote = 800.000 / 4.000.000 = 20 %. Dieser Wert liegt unter dem deutschen Mittelstandsdurchschnitt von ca. 30 %, ist aber für viele KMU-Branchen (z. B. Handel, Bau) noch im plausiblen Bereich. Die Einordnung erfordert immer einen Branchenvergleich und die Zeitreihe.",
    },
    {
      id: "M01-Q5",
      question: "Welche Wirkung hat das Bilanzierungswahlrecht der Sofortabschreibung von geringwertigen Wirtschaftsgütern (GWG, § 6 Abs. 2 EStG) auf den ausgewiesenen Jahresgewinn?",
      options: [
        "A) Es erhöht den Jahresgewinn, weil Investitionen aktiviert werden",
        "B) Es hat keine Auswirkung auf den Jahresgewinn",
        "C) Es senkt den Jahresgewinn durch höhere Abschreibungen",
        "D) Es erhöht die Bilanzsumme durch höhere Vorräte",
      ],
      correctIndex: 2,
      explanation: "Die GWG-Sofortabschreibung erlaubt die vollständige Abschreibung im Anschaffungsjahr statt über die Nutzungsdauer. Das erhöht die Abschreibungen im laufenden Jahr und senkt damit den ausgewiesenen Jahresgewinn — ein defensives Bilanzierungswahlrecht, das Steuer spart, aber das Ergebnis optisch schlechter erscheinen lässt.",
    },
  ],

  "M02": [
    {
      id: "M02-Q1",
      question: "Watzlawick, Beavin und Jackson beschreiben, dass jede Aussage zwei Ebenen enthält. Welche Formulierung zeigt, wie man im Bilanzgespräch die Beziehungsebene schützt?",
      options: [
        "A) 'Ihre EK-Quote ist viel zu niedrig — das ist ein Problem.'",
        "B) 'Sie haben offensichtlich in den letzten Jahren schlecht gewirtschaftet.'",
        "C) 'Ich sehe, dass die EK-Quote von 22 % auf 15 % gefallen ist. Wie erklären Sie sich das?'",
        "D) 'Wir können nur weiter zusammenarbeiten, wenn sich die Kennzahlen verbessern.'",
      ],
      correctIndex: 2,
      explanation: "Das Muster 'Beobachtung + offene Frage' hält die Sachinformation neutral und öffnet den Dialog, anstatt eine Bewertung zu machen, die auf der Beziehungsebene als Vorwurf ankommt. Die anderen Optionen enthalten Bewertungen, die Abwehrhaltungen provozieren.",
    },
    {
      id: "M02-Q2",
      question: "Der 5-Phasen-Rahmen für das Bilanzgespräch sieht in Phase 1 (Vorbereitung) vor, mindestens wie viele Kennzahlen zu berechnen und Vorjahre zu vergleichen?",
      options: [
        "A) 2 Kennzahlen, 1 Vorjahr",
        "B) 4 Kennzahlen, 2 Vorjahre",
        "C) 6 Kennzahlen, 3 Vorjahre",
        "D) 8 Kennzahlen, 5 Vorjahre",
      ],
      correctIndex: 1,
      explanation: "Die Vorbereitung sieht mindestens 4 Kennzahlen (EK-Quote, Liquidität, Verschuldungsgrad, EBIT-Marge) sowie den Vergleich zu mindestens 2 Vorjahren vor, um Trends erkennbar zu machen. Zusätzlich werden 3 Schlüsselbotschaften und 5 offene Fragen schriftlich vorbereitet.",
    },
    {
      id: "M02-Q3",
      question: "Was ist laut Modul M02 die optimale Gesprächsdauer für ein reales Bilanzgespräch beim Kunden vor Ort?",
      options: [
        "A) 30–45 Minuten",
        "B) 60–75 Minuten",
        "C) 120–150 Minuten",
        "D) 180 Minuten (wie das Workshop-Format)",
      ],
      correctIndex: 1,
      explanation: "Für den echten Kundentermin gilt 60–75 Minuten als optimal. Der Unternehmer hat Kunden und Aufträge im Kopf und wird nach 60 Minuten unruhig. Das 180-Minuten-Format im Modul ist ein Übungsformat für den Seminarraum, keine Vorlage für den Kundentermin.",
    },
    {
      id: "M02-Q4",
      question: "Warum reicht eine reine Kennzahlenanalyse laut Krecek (2019) nicht aus, um die Zukunftsfähigkeit eines Unternehmens zu beurteilen?",
      options: [
        "A) Weil Kennzahlen aus dem Jahresabschluss vergangenheitsbezogen und ohne qualitativen Kontext bedeutungslos sind",
        "B) Weil Kennzahlen nur auf HGB-Basis berechnet werden dürfen",
        "C) Weil die BaFin eine reine Kennzahlenanalyse als nicht MaRisk-konform einstuft",
        "D) Weil Jahresabschlüsse kleiner GmbHs keine ausreichende Datenbasis bieten",
      ],
      correctIndex: 0,
      explanation: "Krecek (2019) betont: Die Bilanzanalyse muss in einem Gesprächsprozess mit dem Unternehmen eingebettet sein, da qualitative Faktoren (Managementqualität, Strategie, Marktposition) nur im Dialog erkennbar werden. Kennzahlen sind neutral — sie werden erst aussagekräftig im Kontext.",
    },
    {
      id: "M02-Q5",
      question: "In welcher Phase des 5-Phasen-Rahmens leitet der Berater aus der Bilanzanalyse konkrete Beratungsimpulse für Verbundprodukte ab?",
      options: [
        "A) Phase 1 – Vorbereitung",
        "B) Phase 2 – Eröffnung",
        "C) Phase 3 – Analyse-Dialog",
        "D) Phase 4 – Beratungsimpulse",
      ],
      correctIndex: 3,
      explanation: "Phase 4 dient dazu, aus den Erkenntnissen des Analyse-Dialogs konkrete Produktoptionen abzuleiten — immer aus der Analyse heraus, nicht als produktgetriebenes Push-Selling. So entsteht ein natürlicher, bedarfsorientierter Übergang zu Verbundprodukten.",
    },
  ],

  "M03": [
    {
      id: "M03-Q1",
      question: "Was unterscheidet den 'Strategischen Partner' vom klassischen 'Kreditberater' laut Modul M03?",
      options: [
        "A) Der Strategische Partner hat eine höhere Kreditkompetenz und darf größere Volumina entscheiden",
        "B) Der Strategische Partner richtet seinen Blick auf langfristige Wertsteigerung und erkennt Probleme, bevor der Unternehmer sie formuliert",
        "C) Der Strategische Partner berät ausschließlich Unternehmen ab 50 Mio. EUR Umsatz",
        "D) Der Strategische Partner führt ausschließlich schriftliche Analysen durch",
      ],
      correctIndex: 1,
      explanation: "Der Übergang zum Strategischen Partner bedeutet den Wechsel vom Rückzahlungsrisiko-Fokus zur langfristigen Wertperspektive. Consultative Selling nach Rackham (1988) beschreibt diesen Berater als jemanden, der Probleme des Unternehmers erkennt und löst, bevor dieser sie selbst formuliert.",
    },
    {
      id: "M03-Q2",
      question: "Welcher Fragetyp gehört laut dem Drei-Ebenen-Modell des strategischen Finanzdialogs zur strategischen Ebene?",
      options: [
        "A) 'Wie entwickelt sich Ihr Auftragsbestand im nächsten Quartal?' (Sachstandsfrage)",
        "B) 'Wenn die Marge weiter sinkt – welche Investitionen müssen Sie dann verschieben?' (Implikationsfrage)",
        "C) 'Was wäre der nächste Schritt, wenn Ihre Eigenkapitalquote 30 % überschreitet?' (Zukunftsfrage)",
        "D) 'Welche Kennzahl hat sich in den letzten 3 Jahren am stärksten verändert?' (Analysefrage)",
      ],
      correctIndex: 2,
      explanation: "Die strategische Ebene arbeitet mit Zukunftsfragen ('Was wäre wenn …'), die den Unternehmer zu strategischen Überlegungen einladen. Sachstandsfragen (operativ) und Implikationsfragen (taktisch) bereiten die strategische Ebene vor — zusammen bilden sie das SPIN-Prinzip.",
    },
    {
      id: "M03-Q3",
      question: "Welchen Einfluss hat die Kapitalstruktur eines Unternehmens auf seinen Handlungsspielraum?",
      options: [
        "A) Die Kapitalstruktur beeinflusst nur die Steuerlast, nicht die Investitionsfähigkeit",
        "B) Ein höherer Fremdkapitalanteil erhöht stets die Rendite ohne Risiko",
        "C) Kapitalstrukturentscheidungen wirken direkt auf Unternehmenswert, Risikoprofil und strategische Handlungsfähigkeit",
        "D) Die Kapitalstruktur ist irrelevant, solange der Cashflow positiv ist",
      ],
      correctIndex: 2,
      explanation: "Kapitalstrukturentscheidungen sind keine rein bilanziellen Größen. Sie bestimmen, wie viel Spielraum ein Unternehmen für Investitionen, Krisen und Wachstum hat. Ein zu hoher Verschuldungsgrad schränkt die strategische Handlungsfähigkeit ein und erhöht das Insolvenzrisiko.",
    },
    {
      id: "M03-Q4",
      question: "Rackham (1988) zeigt in seinen SPIN-Studien, welcher Gesprächsanteil bei hochkomplexen B2B-Transaktionen der entscheidende Erfolgsfaktor ist. Welcher ist das?",
      options: [
        "A) Situationsfragen — um schnell ein vollständiges Bild zu bekommen",
        "B) Produktpräsentation — um Vorteile klar zu kommunizieren",
        "C) Implikations- und Nutzenfragen — um den Wert einer Lösung spürbar zu machen",
        "D) Abschlussfragen — um die Entscheidung des Kunden herbeizuführen",
      ],
      correctIndex: 2,
      explanation: "Rackham's SPIN-Forschung zeigt, dass bei komplexen Verkäufen Implikationsfragen (welche Konsequenzen hat das Problem?) und Nutzenfragen (was wäre der Wert einer Lösung?) die entscheidenden Erfolgsfaktoren sind. Situationsfragen und Abschlussfragen spielen eine untergeordnete Rolle.",
    },
    {
      id: "M03-Q5",
      question: "Ein Unternehmer erwägt Mezzanine-Kapital als Alternative zum Bankkredit. Welche Eigenschaft kennzeichnet Mezzanine-Kapital?",
      options: [
        "A) Es ist immer billiger als Bankkredit und hat keine Nachrangigkeit",
        "B) Es kombiniert Merkmale von Eigen- und Fremdkapital und wird bei Insolvenz nachrangig bedient",
        "C) Es erfordert zwingend eine Börsennotierung des Unternehmens",
        "D) Es ist ausschließlich für Unternehmen mit Jahresumsatz über 100 Mio. EUR verfügbar",
      ],
      correctIndex: 1,
      explanation: "Mezzanine-Kapital (z. B. stille Beteiligungen, Nachrangdarlehen, Genussscheine) vereint Eigenschaften von Eigen- und Fremdkapital. Im Insolvenzfall wird es nachrangig zu Bankverbindlichkeiten bedient, was den Zinssatz erhöht. Dafür stärkt es die Eigenkapitalbasis und erweitert den Finanzierungsspielraum.",
    },
  ],

  "M04": [
    {
      id: "M04-Q1",
      question: "Welche der drei Kreditrisikoarten beschreibt die Gefahr, dass die Bonität eines Kreditnehmers sich verschlechtert, ohne dass sofort ein Ausfall eintritt?",
      options: [
        "A) Ausfallrisiko",
        "B) Migrationsrisiko",
        "C) Konzentrationsrisiko",
        "D) Liquiditätsrisiko",
      ],
      correctIndex: 1,
      explanation: "Migrationsrisiko bezeichnet die Verschlechterung des Ratings (Migration von einer besseren zu einer schlechteren Ratingklasse). Obwohl noch kein Ausfall eingetreten ist, steigt das Risikogewicht und damit der Eigenkapitalbedarf der Bank. Beispiel: Ein Mittelständler rutscht von Rating B nach C.",
    },
    {
      id: "M04-Q2",
      question: "Laut empirischen Studien sind 80 % aller Unternehmensinsolvenzen durch Frühwarnindikatoren wie viele Monate vor dem Insolvenzantrag erkennbar?",
      options: [
        "A) 3–6 Monate",
        "B) 6–9 Monate",
        "C) 12–18 Monate",
        "D) 24–36 Monate",
      ],
      correctIndex: 2,
      explanation: "Empirische Studien zeigen, dass 80 % aller Unternehmensinsolvenzen durch Frühwarnindikatoren mindestens 12–18 Monate vor dem Insolvenzantrag erkennbar sind. Das macht Früherkennung zum wirksamsten Instrument zur Verlustminimierung — noch vor der Besicherung.",
    },
    {
      id: "M04-Q3",
      question: "In welcher Krisenphase befindet sich ein Unternehmen, wenn der Kontokorrentrahmen dauerhaft ausgeschöpft ist und erste Zinsverzüge auftreten?",
      options: [
        "A) Phase 1: Potenzielle Krise (gelb)",
        "B) Phase 2: Latente Krise (gelb–rot)",
        "C) Phase 3: Akute/beherrschbare Krise (rot)",
        "D) Phase 4: Insolvenzreife",
      ],
      correctIndex: 2,
      explanation: "Dauerhaft ausgeschöpfter Kontokorrent und Zinsverzüge sind klassische Signale der Phase 3 (akute/beherrschbare Krise). Die Ampel steht auf Rot, sofortige Eskalation ist erforderlich. Phase 2 wäre noch das Haupthandlungsfenster für präventive Maßnahmen.",
    },
    {
      id: "M04-Q4",
      question: "Welches Konzentrationsrisiko beschreibt das folgende Szenario: 35 % des Kreditvolumens einer VR-Bank liegen in der Automobilzulieferer-Branche?",
      options: [
        "A) Ausfallrisiko eines einzelnen Kreditnehmers",
        "B) Migrationsrisiko einer Unternehmensgruppe",
        "C) Branchenkonzentrationsrisiko im Portfolio",
        "D) Regionaler Klumpen durch geografische Konzentration",
      ],
      correctIndex: 2,
      explanation: "35 % Kreditvolumen in einer Branche ist ein typisches Branchenkonzentrationsrisiko: Bei einer Branchenkrise (z. B. Einbruch der Automobilnachfrage) sind überproportional viele Kreditnehmer gleichzeitig betroffen. MaRisk fordert entsprechende Klumpenrisiko-Überwachung.",
    },
    {
      id: "M04-Q5",
      question: "Was ist neben der Verlustminimierung der zweite Grund, warum § 18 KWG die Offenlegung wirtschaftlicher Verhältnisse vorschreibt?",
      options: [
        "A) Um die Steuerpflicht des Kreditnehmers zu überprüfen",
        "B) Als regulatorische Handlungspflicht — die Verweigerung des Jahresabschlusses ist selbst ein Warnsignal",
        "C) Um die Gesellschafterliste für den Bundesanzeiger zu aktualisieren",
        "D) Um die Insolvenzverschleppung des Geschäftsführers zu verhindern",
      ],
      correctIndex: 1,
      explanation: "§ 18 KWG erfüllt eine Doppelfunktion: Er schützt die Bank durch Informationspflicht und signalisiert gleichzeitig, dass die Verweigerung der Unterlagenvorlage durch den Kunden selbst ein Frühwarnsignal ist. In diesem Fall besteht eine regulatorische Handlungspflicht der Bank.",
    },
  ],

  "M05": [
    {
      id: "M05-Q1",
      question: "Welche der fünf Kräfte aus Porter's Five Forces hat die folgende Kreditrelevanz: 'Hohe Markteintrittsbarrieren führen zu geringerem Überangebot und stabileren Margen'?",
      options: [
        "A) Verhandlungsmacht der Abnehmer",
        "B) Bedrohung durch neue Konkurrenten",
        "C) Rivalität unter bestehenden Wettbewerbern",
        "D) Bedrohung durch Substitute",
      ],
      correctIndex: 1,
      explanation: "Die 'Bedrohung durch neue Konkurrenten' hängt von Markteintrittsbarrieren ab. Hohe Barrieren (Kapitalintensität, Skaleneffekte, Markenzugang) bedeuten, dass wenige neue Wettbewerber eintreten können — das stabilisiert Margen und reduziert das Kreditrisiko für die bestehendenUnternehmen.",
    },
    {
      id: "M05-Q2",
      question: "Warum erhöht eine hohe Verhandlungsmacht der Abnehmer (wenige Großkunden) das Kreditrisiko eines KMU?",
      options: [
        "A) Weil die Bank dann höhere Zinsen verlangen muss",
        "B) Weil Verlust eines Großkunden zu massivem Umsatzeinbruch und erhöhter Insolvenzwahrscheinlichkeit führt",
        "C) Weil große Abnehmer immer Insolvenz anmelden",
        "D) Weil die Bilanzsumme bei wenigen Kunden automatisch sinkt",
      ],
      correctIndex: 1,
      explanation: "Hohe Abnehmerkonzentration bedeutet: Fällt ein Großkunde weg, verliert das KMU einen überproportionalen Umsatzanteil. Das ist das klassische Klumpenrisiko auf der Umsatzseite — ein zentraler Kreditrisikotreiber, den die Branchenanalyse nach Porter sichtbar macht.",
    },
    {
      id: "M05-Q3",
      question: "Welche der folgenden Branchen hat typischerweise die höchsten Markteintrittsbarrieren und damit das stabilste Margenprofil für Kreditgeber?",
      options: [
        "A) Einzelhandel ohne Spezialisierung",
        "B) Online-Dienstleistungen ohne Regulierung",
        "C) Sondermaschinenbau mit proprietären Technologien",
        "D) Gastronomie in Innenstadtlage",
      ],
      correctIndex: 2,
      explanation: "Sondermaschinenbau erfordert spezialisiertes Know-how, hohe Kapitalinvestitionen und proprietäre Technologien — klassische Markteintrittsbarrieren. Hohe Barrieren schützen Margen und machen die Branche für Kreditgeber attraktiver als Segmente mit niedrigen Eintrittsbarrieren wie Gastronomie.",
    },
    {
      id: "M05-Q4",
      question: "Was ist das Ziel der branchenspezifischen Risikoklassifikation im Kontext der Kreditvergabe?",
      options: [
        "A) Das Branchenrating vollständig durch das Unternehmensrating zu ersetzen",
        "B) Das strukturelle Risiko einer Branche unabhängig vom einzelnen Unternehmen zu bewerten",
        "C) Die Kreditvergabe an bestimmte Branchen generell zu untersagen",
        "D) Die BaFin-Meldepflicht für Branchenkonzentrationen zu erfüllen",
      ],
      correctIndex: 1,
      explanation: "Die Branchenrisikoanalyse zielt darauf ab, das strukturelle Risiko einer Branche (Wettbewerbsintensität, Margenstruktur, Zyklik) unabhängig vom einzelnen Kreditnehmer zu bewerten. Ein gutes Unternehmen in einer schlechten Branche bleibt risikoreicher als ein gutes Unternehmen in einer stabilen Branche.",
    },
    {
      id: "M05-Q5",
      question: "Ein Firmenkundenberater analysiert einen Kreditantrag eines Druckerei-Unternehmens. Digitaldruck und Online-Medien haben den klassischen Offset-Druck stark unter Druck gesetzt. Welche der fünf Kräfte beschreibt dieses Risiko?",
      options: [
        "A) Rivalität unter bestehenden Wettbewerbern",
        "B) Verhandlungsmacht der Lieferanten",
        "C) Bedrohung durch Substitute",
        "D) Bedrohung durch neue Konkurrenten",
      ],
      correctIndex: 2,
      explanation: "Digitaldruck und Online-Medien sind Substitute für klassischen Offset-Druck — sie erfüllen denselben Kundenbedarf auf alternative Weise. Die 'Bedrohung durch Substitute' beschreibt genau diese Kraft: Wenn Alternativen verfügbar und günstiger/besser sind, verliert die traditionelle Branche Nachfrage und Marge.",
    },
  ],

  "M06": [
    {
      id: "M06-Q1",
      question: "Welche zwei Schwellenwerte definiert das IfM Bonn für ein 'mittleres Unternehmen'?",
      options: [
        "A) 10–249 Mitarbeiter und 2–49,9 Mio. EUR Jahresumsatz",
        "B) 10–499 Mitarbeiter und 2–49,9 Mio. EUR Jahresumsatz",
        "C) 50–249 Mitarbeiter und 10–50 Mio. EUR Jahresumsatz",
        "D) 50–500 Mitarbeiter und 10–100 Mio. EUR Jahresumsatz",
      ],
      correctIndex: 1,
      explanation: "Das IfM Bonn (2024) definiert mittlere Unternehmen als Unternehmen mit 10–499 Mitarbeitern UND 2–49,9 Mio. EUR Jahresumsatz. Beide Kriterien müssen erfüllt sein. Zudem gilt das qualitative Kriterium der Einheit von Eigentum und Leitung.",
    },
    {
      id: "M06-Q2",
      question: "Was ist das qualitative Merkmal, das die IfM-Bonn-Definition von KMU von rein quantitativen Definitionen unterscheidet?",
      options: [
        "A) Der Hauptsitz des Unternehmens in Deutschland",
        "B) Die Einheit von Eigentum und Leitung — der Inhaber führt das Unternehmen selbst",
        "C) Die Mitgliedschaft in einer IHK oder HWK",
        "D) Die Rechtsform als GmbH oder Einzelunternehmen",
      ],
      correctIndex: 1,
      explanation: "Das qualitative Kernmerkmal der IfM-Definition ist die Einheit von Eigentum und Leitung: Der Inhaber führt das Unternehmen selbst und haftet persönlich. Das erklärt das Schlüsselpersonenrisiko, die Verflechtung von Privat- und Betriebsvermögen — und ist für die Kreditanalyse von zentraler Bedeutung.",
    },
    {
      id: "M06-Q3",
      question: "Für welchen praktischen Zweck ist die EU-KMU-Definition besonders relevant im Firmenkundengeschäft?",
      options: [
        "A) Für die Bestimmung der Offenlegungspflicht nach HGB",
        "B) Für EU-Förderprogramme und KfW-Finanzierungsprodukte",
        "C) Für die Klassifizierung als systemrelevantes Institut",
        "D) Für die MaRisk-konforme Risikogewichtung",
      ],
      correctIndex: 1,
      explanation: "Die EU-Definition (Europäische Kommission, 2020) ist die Grundlage für EU-Förderprogramme und KfW-Finanzierungsprodukte. Wer als KMU nach EU-Definition gilt, hat Zugang zu vergünstigten Förderkrediten und staatlichen Garantieprogrammen — direkt relevant für die Beratung.",
    },
    {
      id: "M06-Q4",
      question: "Warum ist das Schlüsselpersonenrisiko bei Inhabergeführten KMU ein besonderes Kreditrisiko?",
      options: [
        "A) Weil der Inhaber oft keine kaufmännische Ausbildung hat",
        "B) Weil Unternehmen und Inhaberperson eng verknüpft sind — fällt der Inhaber aus, fehlt oft auch die unternehmerische Führung",
        "C) Weil Inhabergeführte KMU keine Vertretungsregelung in der GmbH-Satzung haben dürfen",
        "D) Weil die Bank haftet, wenn der Inhaber strafrechtlich verurteilt wird",
      ],
      correctIndex: 1,
      explanation: "Bei der Einheit von Eigentum und Leitung ist der Inhaber oft gleichzeitig Stratege, Vertriebschef und Hauptkunde-Kontakt. Fällt er durch Krankheit, Tod oder Unfall aus, bricht häufig auch das Geschäftsmodell ein. Das Schlüsselpersonenrisiko ist daher ein Kernbestandteil der KMU-Kreditanalyse.",
    },
    {
      id: "M06-Q5",
      question: "Das 5-Fragen-Schema zur KMU-Einordnung hilft dem Berater, einen neuen Kunden schnell zu verstehen. Welche der folgenden Fragen gehört NICHT zum Schema?",
      options: [
        "A) Was ist das Geschäftsmodell — wie verdient das Unternehmen Geld?",
        "B) Wer sind die wichtigsten Kunden und wie konzentriert ist der Umsatz?",
        "C) Welche Branche, und welche strukturellen Risiken bringt sie mit?",
        "D) Welche Gesellschafterstruktur und welches Stammkapital hat die GmbH?",
      ],
      correctIndex: 3,
      explanation: "Das 5-Fragen-Schema zielt auf Geschäftsmodell, Kundenbasis, Branchencharakteristika, Finanzierungsstruktur und Schlüsselpersonen — nicht auf rechtliche Formalien wie Stammkapital. Gesellschafterstruktur ist zwar relevant, aber das Stammkapital allein hilft bei der ersten Einordnung kaum.",
    },
  ],

  "M07": [
    {
      id: "M07-Q1",
      question: "Was ist der praktische Unterschied für den Firmenkundenberater, wenn ein Kunde Freiberufler (§ 18 EStG) statt Gewerbetreibender ist?",
      options: [
        "A) Freiberufler müssen keine Steuern zahlen",
        "B) Freiberufler sind von der Gewerbesteuer befreit und können EÜR statt Bilanz einreichen",
        "C) Freiberufler unterliegen strengerer Bankenaufsicht nach KWG",
        "D) Freiberufler haben keine Offenlegungspflicht gegenüber der Bank",
      ],
      correctIndex: 1,
      explanation: "Freiberufler nach § 18 EStG zahlen keine Gewerbesteuer und sind bis 600.000 EUR Umsatz von der handelsrechtlichen Bilanzierungspflicht befreit — sie reichen eine Einnahmen-Überschuss-Rechnung (EÜR) ein. Das ändert die Analysebasis für den Kreditberater grundlegend.",
    },
    {
      id: "M07-Q2",
      question: "Wie wird der Goodwill einer Arztpraxis nach der modifizierten Ertragswertmethode (IDW S5) grundsätzlich ermittelt?",
      options: [
        "A) Als Differenz zwischen Bilanzsumme und Verbindlichkeiten",
        "B) Als Barwert der zukünftig erwarteten Überschüsse über einen risikogerechten Zinssatz, abzüglich Substanzwert",
        "C) Als Vielfaches des letzten Jahresumsatzes",
        "D) Als Summe aller aktivierten immateriellen Vermögensgegenstände laut Bilanz",
      ],
      correctIndex: 1,
      explanation: "Die modifizierte Ertragswertmethode (IDW S5) ermittelt den Goodwill als Barwert der nachhaltig erzielbaren Überschüsse (Ertragswert), abzüglich des Substanzwertes (Inventar, Einrichtung). Der Goodwill ist der immateriell Wert — die Patientenbindung, der Ruf, die Lage.",
    },
    {
      id: "M07-Q3",
      question: "Was unterscheidet eine Berufsausübungsgemeinschaft (BAG) von einem Medizinischen Versorgungszentrum (MVZ) aus kreditanalytischer Sicht?",
      options: [
        "A) Die BAG darf nur in einer Rechtsform als GmbH geführt werden, das MVZ nicht",
        "B) Im MVZ können auch Nicht-Ärzte Gesellschafter sein und angestellte Ärzte tätig sein — die persönliche Zulassung ist vom Unternehmen getrennt",
        "C) Das MVZ unterliegt nicht dem § 18 KWG",
        "D) In der BAG gibt es kein Schlüsselpersonenrisiko, im MVZ schon",
      ],
      correctIndex: 1,
      explanation: "Im MVZ können Nicht-Ärzte (z. B. Klinikträger) Gesellschafter sein, und die ärztliche Tätigkeit wird durch angestellte Ärzte erbracht — die Kassenzulassung liegt beim MVZ, nicht bei der Person. Das verändert das Risikoprofil erheblich: weniger Schlüsselpersonenrisiko, aber komplexere Governance.",
    },
    {
      id: "M07-Q4",
      question: "Warum ist das Zulassungsrisiko bei Heilberufskunden ein besonders relevantes Kreditrisiko?",
      options: [
        "A) Weil die Zulassung jährlich neu beantragt werden muss und hohe Gebühren kostet",
        "B) Weil bei Entzug der Kassenzulassung der wesentliche Umsatzstrom wegbricht und die Kreditfähigkeit schlagartig entfällt",
        "C) Weil die Zulassungsausschüsse keine Auskunft an Banken geben",
        "D) Weil Heilberufe nach § 18 KWG nicht als Unternehmen gelten",
      ],
      correctIndex: 1,
      explanation: "Die Kassenzulassung ist die Existenzberechtigung für den Großteil des Umsatzes eines Arztes oder Apothekers. Entzug oder Rückgabe der Zulassung (z. B. bei Disziplinarverfahren) bedeutet sofortigen Umsatzeinbruch um häufig 70–90 %. Kreditrückzahlung ist dann kaum mehr möglich.",
    },
    {
      id: "M07-Q5",
      question: "Was ist bei der Analyse einer EÜR (Einnahmen-Überschuss-Rechnung) eines Arztes besonders zu beachten im Vergleich zur handelsrechtlichen GuV?",
      options: [
        "A) Die EÜR weist immer einen höheren Gewinn aus als die GuV",
        "B) Die EÜR folgt dem Zufluss-/Abflussprinzip — Einnahmen und Ausgaben werden bei Zahlung erfasst, nicht bei Entstehung",
        "C) Die EÜR ist nur für die Steuererklärung relevant und hat keine Kreditrelevanz",
        "D) Die EÜR enthält keine Abschreibungen, da Freiberufler keine Investitionen tätigen",
      ],
      correctIndex: 1,
      explanation: "Die EÜR basiert auf dem Zufluss-/Abflussprinzip (Kassenprinzip): Einnahmen werden bei Zufluss, Ausgaben bei Abfluss erfasst. Das kann zu signifikanten Verschiebungen im Vergleich zur periodengerechten GuV führen — z. B. wenn Honorare spät gezahlt werden. Für die Schuldendienstanalyse muss der Berater das berücksichtigen.",
    },
  ],

  "M08": [
    {
      id: "M08-Q1",
      question: "Was ist der wesentliche Unterschied im Cashflow-Profil eines Bauträgers gegenüber einem Bestandshalter?",
      options: [
        "A) Der Bauträger hat stabile Mieteinnahmen, der Bestandshalter volatile Projekteingänge",
        "B) Beim Bauträger fließt der Cashflow erst am Projektende durch Verkaufserlöse — nicht durch laufende Mieten",
        "C) Der Bauträger unterliegt dem Beleihungswertverfahren, der Bestandshalter nicht",
        "D) Bestandshalter haben kein Zinsänderungsrisiko, Bauträger schon",
      ],
      correctIndex: 1,
      explanation: "Der Bauträger entwickelt, verkauft und zieht sich dann zurück — kein laufender Cashflow, sondern Projekterlöse am Ende. Das erhöht das Liquiditätsrisiko während der Bauphase erheblich. Der Bestandshalter hingegen finanziert sich aus stabilen Mieteinnahmen.",
    },
    {
      id: "M08-Q2",
      question: "Was misst der DSCR (Debt Service Coverage Ratio) bei der Immobilienfinanzierung?",
      options: [
        "A) Den Beleihungsauslauf (Kredit zu Immobilienwert)",
        "B) Ob die Mieteinnahmen ausreichen, um Zinsen und Tilgung des Darlehens zu decken",
        "C) Die Nettoanfangsrendite im Verhältnis zum Kaufpreis",
        "D) Das Verhältnis von Eigenkapital zu Gesamtinvestition",
      ],
      correctIndex: 1,
      explanation: "DSCR = Nettomieteinnahmen / Kapitaldienst (Zins + Tilgung). Ein DSCR > 1,2 gilt als Mindestanforderung — das Mietaufkommen übersteigt den Kapitaldienst um 20 % als Puffer. Der DSCR ist die zentrale Kennzahl für Bestandshalterfinanzierungen.",
    },
    {
      id: "M08-Q3",
      question: "Nach welchem Prinzip wird der Beleihungswert gemäß BelWertV ermittelt, und warum ist er für Kreditgeber wichtiger als der Verkehrswert?",
      options: [
        "A) Er wird als Durchschnitt der letzten 5 Verkaufspreise in der Region ermittelt und ist damit aktueller",
        "B) Er ist ein nachhaltiger, marktunabhängiger Wert — er zeigt, was die Immobilie auch in schlechten Marktphasen wert ist",
        "C) Er entspricht dem steuerlichen Einheitswert laut Grundsteuergesetz",
        "D) Er liegt immer 30 % über dem Verkehrswert als Sicherheitspuffer",
      ],
      correctIndex: 1,
      explanation: "Der Beleihungswert nach BelWertV ist ein langfristig nachhaltiger, konjunkturunabhängiger Wert. Er berücksichtigt nur nachhaltige Mieteinnahmen und schließt spekulative Preisspitzen aus. Für Kreditgeber ist er relevanter als der aktuelle Verkehrswert, weil er zeigt, was die Sicherheit auch in Krisenzeiten wert ist.",
    },
    {
      id: "M08-Q4",
      question: "Bei welchem Immobilienkundentypus trägt die Bank das höchste Fertigstellungsrisiko?",
      options: [
        "A) Bestandshalter mit vollvermieteter Gewerbeimmobilie",
        "B) Projektentwickler in der frühen Entwicklungsphase",
        "C) Wohnungsgesellschaft mit bestehendem Portfolio",
        "D) Arztpraxis-Betreiber als Eigennutzer",
      ],
      correctIndex: 1,
      explanation: "Projektentwickler stehen in der frühen Phase vor dem größten Risiko: keine Baugenehmigung, kein Mieter, kein Verkäufer — nur Planung und Bodenankauf. Das Fertigstellungsrisiko ist maximal. Bestandshalter und Eigennutzer haben bereits laufende Cashflows, die das Risiko stark reduzieren.",
    },
    {
      id: "M08-Q5",
      question: "Was beschreibt die Nettoanfangsrendite (NAR) bei Immobilien?",
      options: [
        "A) Den jährlichen Zinsaufwand im Verhältnis zur Bilanzsumme",
        "B) Die jährlichen Nettomieteinnahmen im Verhältnis zum Kaufpreis der Immobilie",
        "C) Die Eigenkapitalrendite nach Steuern beim Immobilienkauf",
        "D) Den Abschreibungssatz auf das Gebäude nach AfA-Tabelle",
      ],
      correctIndex: 1,
      explanation: "Nettoanfangsrendite = Jahresnettomiete / Kaufpreis. Sie zeigt, wie viel Prozent des Kaufpreises jährlich als Miete zurückfließen. Je höher die NAR, desto attraktiver die Immobilie für Investoren und desto besser die Tragfähigkeit des Kapitaldienstes.",
    },
  ],

  "M09": [
    {
      id: "M09-Q1",
      question: "Welches Analyseinstrument kombiniert Modul M09 mit Porter's Five Forces für eine vollständige Branchenanalyse?",
      options: [
        "A) Balanced Scorecard",
        "B) PESTEL-Analyse",
        "C) SWOT-Analyse",
        "D) Benchmarking",
      ],
      correctIndex: 1,
      explanation: "M09 kombiniert Porter's Five Forces (Wettbewerbsstruktur) mit der PESTEL-Analyse (Political, Economic, Social, Technological, Environmental, Legal), um sowohl die Branchenstruktur als auch das Makroumfeld systematisch zu erfassen — eine vollständige Grundlage für Branchenexpertise.",
    },
    {
      id: "M09-Q2",
      question: "Was ist das Kernziel des 3-Monats-Plans zum Aufbau von Branchenexpertise in Modul M09?",
      options: [
        "A) In drei Monaten ein vollständiges Branchenrating für alle Kunden zu erstellen",
        "B) Strukturiert Informationsquellen zu erschließen, ein Netzwerk aufzubauen und ein Branchenportfolio zu dokumentieren",
        "C) Die NMZ im Zielsegment um 20 % zu steigern",
        "D) Einen Fachartikel in einer Branchenpublikation zu veröffentlichen",
      ],
      correctIndex: 1,
      explanation: "Der 3-Monats-Plan fokussiert auf drei parallele Aktivitäten: systematische Informationserschließung (Quellen, Publikationen), Netzwerkaufbau zu Branchenexperten und Verbänden sowie die Dokumentation im Branchenportfolio. Das Ziel ist nachhaltige Expertise, nicht kurzfristige Kennzahlverbesserung.",
    },
    {
      id: "M09-Q3",
      question: "Was unterscheidet den Branchenexperten im Firmenkundengeschäft vom generalistischen Berater?",
      options: [
        "A) Der Branchenexperte hat eine höhere Kreditkompetenz und darf mehr entscheiden",
        "B) Der Branchenexperte kennt typische Kennzahlen, Risikotreiber und Netzwerke einer Branche und kann Unternehmen besser einordnen und beraten",
        "C) Der Branchenexperte ist ausschließlich für Großunternehmen zuständig",
        "D) Der Branchenexperte hat eine spezielle BaFin-Zulassung",
      ],
      correctIndex: 1,
      explanation: "Branchenexpertise ermöglicht es dem Berater, Abweichungen von Branchennormen sofort zu erkennen, branchenspezifische Risiken zu gewichten und mit Unternehmern auf Augenhöhe zu sprechen. Das schafft Vertrauen und differenziert von Wettbewerbsbanken, die generalistisch beraten.",
    },
    {
      id: "M09-Q4",
      question: "Welche Informationsquelle für Branchenwissen ist laut Modul M09 besonders wertvoll, aber zeitverzögert?",
      options: [
        "A) IHK-Newsletter",
        "B) Bundesbank Unternehmensabschlussstatistik",
        "C) LinkedIn-Branchengruppen",
        "D) agree-Frühwarnberichte",
      ],
      correctIndex: 1,
      explanation: "Die Bundesbank Unternehmensabschlussstatistik ist kostenlos verfügbar und liefert belastbare Branchenkennzahlen — ist aber oft 2 Jahre zeitverzögert. Für aktuellere Daten empfiehlt das Modul die Creditreform/Bisnode-Branchenbenchmarks, die in agree direkt abrufbar sind.",
    },
    {
      id: "M09-Q5",
      question: "Wozu dient das 'Branchenportfolio' als Dokumentationsinstrument in Modul M09?",
      options: [
        "A) Als Pflichtdokumentation für den MaRisk-Bericht der Bank",
        "B) Als persönliches Wissensmanagement-Tool, das Erkenntnisse, Quellen und Netzwerkkontakte einer Branche strukturiert sammelt",
        "C) Als Kreditentscheidungsunterlage für den Kreditausschuss",
        "D) Als Grundlage für das jährliche Mitarbeitergespräch",
      ],
      correctIndex: 1,
      explanation: "Das Branchenportfolio ist ein persönliches Werkzeug des Beraters — es hält Branchenkenntnisse, relevante Quellen, Schlüsselkontakte und Lessons Learned aus Kundengesprächen fest. Es wächst mit der Erfahrung und ist die Grundlage dafür, langfristig als Branchenexperte wahrgenommen zu werden.",
    },
  ],

  "M10": [
    {
      id: "M10-Q1",
      question: "Das Vier-Ohren-Modell nach Schulz von Thun beschreibt vier Kommunikationsebenen. Welche Ebene meint der Unternehmer, wenn er sagt: 'Wir hatten letztes Jahr einen starken Einbruch'?",
      options: [
        "A) Nur die Sachinhalt-Ebene — er teilt eine Tatsache mit",
        "B) Alle vier Ebenen gleichzeitig — Sachinhalt, Beziehung, Selbstoffenbarung und Appell",
        "C) Nur die Appell-Ebene — er bittet um Hilfe",
        "D) Nur die Beziehungsebene — er testet, ob der Berater Verständnis zeigt",
      ],
      correctIndex: 1,
      explanation: "Jede Aussage enthält laut Schulz von Thun gleichzeitig vier Botschaften: Sachinhalt (Umsatzeinbruch), Selbstoffenbarung (Sorge, Unsicherheit), Beziehungsbotschaft (Vertrauen zum Berater?) und Appell (Hilf mir / versteh mich). Der Berater muss alle vier Ebenen wahrnehmen, nicht nur den Sachinhalt.",
    },
    {
      id: "M10-Q2",
      question: "Was ist der UnternehmerDialog als Instrument im Modul M10?",
      options: [
        "A) Ein digitales CRM-Tool in agree für Gesprächsdokumentation",
        "B) Ein strukturierter Gesprächsrahmen, der alle relevanten Bedarfsdimensionen eines Firmenkundengesprächs systematisch erschließt",
        "C) Ein Rollenspiel-Format für die interne Weiterbildung",
        "D) Ein gesetzlich vorgeschriebenes Format für Jahresgespräche",
      ],
      correctIndex: 1,
      explanation: "Der UnternehmerDialog ist ein strukturierter Leitfaden, der sicherstellt, dass der Berater alle relevanten Dimensionen des Kundengesprächs (Unternehmen, Finanzierung, Absicherung, Vorsorge, Nachfolge) systematisch erschließt — und nichts Wesentliches vergisst.",
    },
    {
      id: "M10-Q3",
      question: "Was bedeutet es, den 'Vollständigkeitsgrad' einer Bedarfsanalyse zu bewerten?",
      options: [
        "A) Zu prüfen, ob alle Pflichtfelder im agree-Formular ausgefüllt wurden",
        "B) Einzuschätzen, welche Bedarfsdimensionen im Gespräch erschlossen wurden und welche noch offen sind",
        "C) Zu zählen, wie viele Produkte dem Kunden angeboten wurden",
        "D) Den Deckungsbeitrag des Kunden mit dem Bestandsdurchschnitt zu vergleichen",
      ],
      correctIndex: 1,
      explanation: "Der Vollständigkeitsgrad beschreibt, wie viele der relevanten Bedarfsdimensionen im Gespräch tatsächlich erkundet wurden. Ein hoher Vollständigkeitsgrad bedeutet: Der Berater hat nicht nur das Offensichtliche abgefragt, sondern auch latente Bedarfe und zukünftige Veränderungen angesprochen.",
    },
    {
      id: "M10-Q4",
      question: "Welches Problem tritt auf, wenn ein Berater im Kundengespräch ausschließlich auf der Sachinhalt-Ebene hört?",
      options: [
        "A) Er verletzt die DSGVO, weil er zu viele Daten erhebt",
        "B) Er übersieht Selbstoffenbarung, Beziehungsbotschaften und Appelle — und damit den eigentlichen Bedeutungsrahmen hinter sachlichen Aussagen",
        "C) Er stellt zu viele offene Fragen und verlängert das Gespräch unnötig",
        "D) Er dokumentiert zu viel in agree und verletzt Datenschutzbestimmungen",
      ],
      correctIndex: 1,
      explanation: "Wer nur sachlich hört, verpasst das Wesentliche: Was beschäftigt den Unternehmer wirklich? Welche Sorgen schwingen mit? Welche unausgesprochene Bitte steckt hinter der Aussage? Diese Ebenen entscheiden, ob ein Gespräch Vertrauen aufbaut oder rein transaktional bleibt.",
    },
    {
      id: "M10-Q5",
      question: "Welche Fragetechnik sollte der Berater einsetzen, um Bedarfsdimensionen zu erschließen, ohne die Richtung des Gesprächs zu sehr zu steuern?",
      options: [
        "A) Geschlossene Fragen für schnelle Datenerhebung",
        "B) Suggestivfragen, um Produkte zu platzieren",
        "C) Offene Fragen, die dem Kunden Raum geben, seinen Bedeutungsrahmen zu entfalten",
        "D) Rhetorische Fragen, die die Antwort bereits implizieren",
      ],
      correctIndex: 2,
      explanation: "Offene Fragen (W-Fragen: Wie, Was, Warum, Womit) laden den Kunden ein, seinen eigenen Rahmen zu beschreiben, ohne dass der Berater eine Richtung vorgibt. Das ist die Grundtechnik zur Erschließung latenter Bedarfe und zur Kommunikation auf allen vier Ebenen.",
    },
  ],

  "M11": [
    {
      id: "M11-Q1",
      question: "Was ist der Unterschied zwischen einem expliziten und einem latenten Bedarf laut Rackham (1988)?",
      options: [
        "A) Explizite Bedarfe betreffen Kredite, latente Bedarfe betreffen Versicherungen",
        "B) Explizite Bedarfe sind klar geäußerte Wünsche, latente Bedarfe sind unbewusste oder nicht artikulierte Problemlagen",
        "C) Latente Bedarfe sind nur für Großunternehmen relevant",
        "D) Explizite Bedarfe entstehen im Jahresgespräch, latente erst nach dem Abschluss",
      ],
      correctIndex: 1,
      explanation: "Rackham (1988) unterscheidet: Explizite Bedarfe sind klar geäußerte Wünsche ('Ich brauche einen Investitionskredit'). Latente Bedarfe sind unbewusste Problemlagen oder Unzufriedenheiten, die der Kunde noch nicht als Bedarf formuliert hat. Sie zu erkennen ist die Königsdisziplin der Bedarfsanalyse.",
    },
    {
      id: "M11-Q2",
      question: "Die SPIN-Fragetechnik besteht aus vier Fragetypen. Was ist das Ziel einer 'Implikationsfrage'?",
      options: [
        "A) Die Situation des Kunden zu erfassen",
        "B) Das Problem zu benennen",
        "C) Die Konsequenzen des Problems spürbar zu machen, damit der Handlungsdruck steigt",
        "D) Den Nutzen der Lösung zu kommunizieren",
      ],
      correctIndex: 2,
      explanation: "Implikationsfragen ('Was passiert, wenn dieses Problem nicht gelöst wird?') vertiefen das Problembewusstsein und machen den Handlungsdruck spürbar. Sie bauen auf Problem-Fragen auf und bereiten die Nutzenfragen vor — Rackham zeigt, dass sie der entscheidende Erfolgsfaktor bei komplexen Verkäufen sind.",
    },
    {
      id: "M11-Q3",
      question: "Ein Unternehmer sagt: 'Eigentlich läuft alles gut, nur die Zahlungsmoral unserer Kunden nervt manchmal.' Was signalisiert diese Aussage?",
      options: [
        "A) Kein Bedarf — alles ist in Ordnung",
        "B) Ein latentes Signal für möglichen Liquiditätsbedarf und potenziellen Forderungsfinanzierungsbedarf",
        "C) Der Unternehmer möchte kein Gespräch über Finanzen führen",
        "D) Ein expliziter Bedarf nach einem Kontokorrentkredit",
      ],
      correctIndex: 1,
      explanation: "Die Aussage ist ein klassisches latentes Signal: Der Unternehmer formuliert kein Finanzprodukt, beschreibt aber ein Problem (schlechte Zahlungsmoral), das auf Liquiditätsengpässe hinweist. Das öffnet Türen für Factoring, Lieferantenkredit-Optimierung oder Kontokorrent-Erweiterung.",
    },
    {
      id: "M11-Q4",
      question: "Das Eisberg-Modell der Kundenbedürfnisse besagt, welchen Anteil der Bedarfe ein Kunden typischerweise explizit äußert?",
      options: [
        "A) Nahezu alle Bedarfe — was nicht geäußert wird, ist kein Bedarf",
        "B) Ca. 20 % — der Rest liegt unterhalb der Oberfläche als latente Bedürfnisse",
        "C) Genau 50 % — latent und explizit halten sich die Waage",
        "D) Über 80 % — latente Bedarfe sind die Ausnahme",
      ],
      correctIndex: 1,
      explanation: "Das Eisberg-Modell zeigt: Nur der sichtbare Teil (ca. 20 %) wird explizit geäußert. Der weitaus größere Teil liegt unter der Oberfläche — das sind unbewusste Bedürfnisse, Ängste und Wünsche, die erst durch gezielte Fragetechniken sichtbar werden.",
    },
    {
      id: "M11-Q5",
      question: "Welches paraverbale Signal kann ein latentes Unbehagen anzeigen, das der Unternehmer sachlich nicht äußert?",
      options: [
        "A) Lautes und klares Sprechen",
        "B) Häufiges Zögern, Satzabbrüche oder ein plötzlicher Themenwechsel",
        "C) Direkter Blickkontakt und aufrechte Sitzhaltung",
        "D) Detaillierte und strukturierte Antworten",
      ],
      correctIndex: 1,
      explanation: "Paraverbale Signale wie Zögern, Satzabbrüche oder abrupte Themenwechsel können auf Themen hinweisen, bei denen der Unternehmer unsicher oder belastet ist — z. B. wenn es um Nachfolge, Gesellschafterkonflikte oder finanzielle Schwierigkeiten geht. Aktives Zuhören erfasst auch diese Ebene.",
    },
  ],

  "M12": [
    {
      id: "M12-Q1",
      question: "Welche der folgenden Nachfolgeoptionen ist typischerweise mit dem geringsten Verkaufserlös für den Unternehmer verbunden, bietet aber die höchste Kontinuität für Mitarbeiter und Unternehmenskultur?",
      options: [
        "A) Strategischer Verkauf an einen Wettbewerber",
        "B) Börsengang (IPO)",
        "C) Familieninterne Nachfolge",
        "D) Management-Buy-Out (MBO)",
      ],
      correctIndex: 2,
      explanation: "Die familieninterne Nachfolge maximiert die Kontinuität (Kultur, Werte, Mitarbeiterbindung), führt aber häufig zu günstigeren Übertragungswegen (Schenkung, Erbfolge), die den realisierten Erlös reduzieren. Strategische Käufer zahlen meist mehr, weil sie Synergien einpreisen.",
    },
    {
      id: "M12-Q2",
      question: "Was sind laut Modul M12 drei bewährte Anlässe, um das Thema Nachfolge bei einem Bestandskunden erstmalig anzusprechen?",
      options: [
        "A) Kreditantrag, Ratinggespräch, Jahresabschlussvorlage",
        "B) Jahresgespräch, nach einem persönlichen Lebens-Event, aus einem Marktgespräch heraus",
        "C) Neue Bankprodukte, Zinsentwicklung, regulatorische Änderungen",
        "D) Mitarbeiterpension, Unternehmensinsolvenz eines Wettbewerbers, Steuernachzahlung",
      ],
      correctIndex: 1,
      explanation: "M12 beschreibt drei natürliche Einstiegs-Anlässe: das Jahresgespräch (immer möglich), ein persönliches Lebens-Event (runder Geburtstag, Krankheit) und ein Marktgespräch (z. B. Nachfolge eines Mitbewerbers). Diese Anlässe schaffen einen glaubwürdigen, nicht aufgesetzten Einstieg in das Thema.",
    },
    {
      id: "M12-Q3",
      question: "Systemische und zirkuläre Fragen werden im CEO-Dialog eingesetzt. Was ist das Ziel einer zirkulären Frage?",
      options: [
        "A) Den Kunden zur Unterschrift zu bewegen",
        "B) Die Sichtweise anderer Beteiligter zu aktivieren und Außenperspektiven einzubeziehen",
        "C) Das Rating des Unternehmens zu verbessern",
        "D) Rechtliche Risiken der Nachfolge zu klären",
      ],
      correctIndex: 1,
      explanation: "Zirkuläre Fragen fragen nach der Perspektive anderer: 'Was würde Ihre Frau sagen, wenn Sie heute die Nachfolge regeln würden?' Sie durchbrechen die Ich-Perspektive des Unternehmers und bringen neue Sichtweisen ins Gespräch — oft kommen dabei latente Konflikte und Ängste zum Vorschein.",
    },
    {
      id: "M12-Q4",
      question: "Warum ist die emotionale Bereitschaft zur Übergabe oft die größte Hürde bei Unternehmensnachfolgen?",
      options: [
        "A) Weil Unternehmer grundsätzlich kein Interesse an Steueroptimierung haben",
        "B) Weil das Unternehmen oft die zentrale Lebensidentität des Inhabers ist — Loslassen bedeutet Identitätsverlust",
        "C) Weil Nachfolger rechtlich nicht zur Übernahme verpflichtet werden können",
        "D) Weil Banken keine Finanzierung für Nachfolger anbieten dürfen",
      ],
      correctIndex: 1,
      explanation: "Für viele Inhaberunternehmer ist das Unternehmen mehr als ein Wirtschaftsgut — es ist Lebenswerk, soziales Netzwerk und Identität. Die Vorstellung loszulassen, löst Angst vor dem Bedeutungsverlust aus. Erst wenn der Berater diese emotionale Dimension adressiert, können sachliche Planungsschritte greifen.",
    },
    {
      id: "M12-Q5",
      question: "Was umfasst eine vollständige Nachfolge-Roadmap laut Modul M12?",
      options: [
        "A) Nur den Kaufpreis und die Finanzierungsstruktur",
        "B) Finanzierungs-, Steuer- und emotionale Meilensteine über einen Zeitraum von 3–7 Jahren",
        "C) Den Gesellschaftsvertrag und die Handelsregistereintragung",
        "D) Ausschließlich die steuerliche Optimierung des Veräußerungsgewinns",
      ],
      correctIndex: 1,
      explanation: "Eine professionelle Nachfolge-Roadmap integriert Finanzierungsmeilensteine (Kaufpreiszahlung, Ablösung Altverbindlichkeiten), Steuermeilensteine (Übergabezeitpunkt, Freibeträge) und emotionale Meilensteine (Rückzug des Seniors, Autoritätsübertragung). Nur alle drei Dimensionen zusammen sichern eine erfolgreiche Übergabe.",
    },
  ],

  "M13": [
    {
      id: "M13-Q1",
      question: "Was ist der Unterschied zwischen reaktivem und systematisch-bedarfsorientiertem Cross-Selling?",
      options: [
        "A) Reaktives Cross-Selling nutzt digitale Kanäle, bedarfsorientiertes nutzt persönliche Gespräche",
        "B) Reaktives Cross-Selling reagiert auf Kundenwünsche; bedarfsorientiertes Cross-Selling identifiziert Bedarfe proaktiv auf Basis der Kundenanalyse",
        "C) Reaktives Cross-Selling ist günstiger, bedarfsorientiertes teurer",
        "D) Reaktives Cross-Selling ist MaRisk-konform, bedarfsorientiertes nicht",
      ],
      correctIndex: 1,
      explanation: "Reaktives Cross-Selling wartet, bis der Kunde einen Bedarf äußert. Bedarfsorientiertes Cross-Selling analysiert proaktiv das Kundenprofil (Branche, Lebensphase, Portfolio), um Bedarfe zu antizipieren, bevor der Kunde sie formuliert. Das zweite Modell ist nachhaltiger und schafft echten Mehrwert.",
    },
    {
      id: "M13-Q2",
      question: "Was misst die Wallet-Share-Methodik im Cross-Selling-Kontext?",
      options: [
        "A) Den Anteil des Kunden am Gesamtbestand der Bank",
        "B) Den Anteil der Bank am gesamten Finanzierungsvolumen des Kunden (Marktanteil pro Kunde)",
        "C) Den Deckungsbeitrag des Kunden im Vergleich zum Branchendurchschnitt",
        "D) Das Potenzial für digitale Produkte beim Kunden",
      ],
      correctIndex: 1,
      explanation: "Wallet Share bezeichnet den Anteil, den die eigene Bank am gesamten 'Geldbeutel' des Kunden hat — also wie viel Prozent des gesamten Finanzierungsvolumens, der Absicherungsprodukte und Anlagegelder bei der eigenen Bank liegen. Ein niedriger Wallet Share zeigt Cross-Selling-Potenzial auf.",
    },
    {
      id: "M13-Q3",
      question: "Welcher Verbundpartner ist bei Firmenkundenbedarfen im Bereich gewerbliche Absicherung (z. B. Betriebshaftpflicht, Kreditausfallschutz) der primäre Ansprechpartner?",
      options: [
        "A) Union Investment",
        "B) DZ Bank",
        "C) R+V Versicherung",
        "D) Schwäbisch Hall",
      ],
      correctIndex: 2,
      explanation: "R+V ist der Versicherungsverbundpartner der VR-Banken und deckt gewerbliche Versicherungsbedarfe ab (Betriebshaftpflicht, Kreditausfallversicherung, Cyber, Gebäude). Union Investment = Kapitalanlage, DZ Bank = Kapitalmarkt/Derivate, Schwäbisch Hall = Bausparen/private Baufinanzierung.",
    },
    {
      id: "M13-Q4",
      question: "Der 4-Schritte-Cross-Selling-Prozess beginnt mit der Analyse. Was ist der zweite Schritt?",
      options: [
        "A) Direktes Produktangebot",
        "B) Hypothesenbildung — eine bedarfsorientierte Arbeitshypothese über den wahrscheinlichsten nächsten Bedarf",
        "C) Dokumentation in agree",
        "D) Einholung eines Konkurrenzangebots",
      ],
      correctIndex: 1,
      explanation: "Nach der Analyse folgt die Hypothesenbildung: Auf Basis des Kundenprofils formuliert der Berater eine Arbeitshypothese ('Dieser Kunde hat vermutlich einen Absicherungsbedarf für seine Exportrisiken'). Erst danach kommt das strukturierte Gespräch — und am Ende die Dokumentation.",
    },
    {
      id: "M13-Q5",
      question: "Warum ist produktgetriebenes Push-Cross-Selling langfristig weniger erfolgreich als bedarfsorientiertes Cross-Selling?",
      options: [
        "A) Weil Produkte gesetzlich nicht aktiv angeboten werden dürfen",
        "B) Weil es die Kundenbeziehung belastet und als aufdringlich empfunden wird, wenn kein echter Bedarf besteht",
        "C) Weil Push-Selling in agree nicht dokumentiert werden kann",
        "D) Weil Verbundpartner nur bei Bedarfsorientierung Provision zahlen",
      ],
      correctIndex: 1,
      explanation: "Push-Cross-Selling — das Anbieten von Produkten unabhängig vom Kundenbedarf — führt zu Ablehnung und beschädigt das Vertrauen. Wenn Kunden das Gefühl bekommen, nur als Umsatzziel betrachtet zu werden, rücken sie ab. Bedarfsorientiertes Cross-Selling schafft dagegen Mehrwert und stärkt die Bindung.",
    },
  ],

  "M14": [
    {
      id: "M14-Q1",
      question: "Was besagt die empirische Beobachtung der zeb-Firmenkundenstudie zur Ertragsverteilung im Firmenkundenbestand?",
      options: [
        "A) Alle Kunden tragen gleichmäßig zum Deckungsbeitrag bei",
        "B) 20 % der Kunden erzeugen 80 % des Deckungsbeitrags",
        "C) 50 % der Kunden sind nicht profitabel",
        "D) Neukunden sind immer ertragreicher als Bestandskunden",
      ],
      correctIndex: 1,
      explanation: "Die zeb-Studie zeigt die klassische 80/20-Verteilung: 20 % der Kunden generieren 80 % des Deckungsbeitrags. Ohne Ertragsanalyse investieren Berater Zeit und Kapital in ertragsschwache Kunden, während ertragstarke Kunden zu wenig Aufmerksamkeit erhalten.",
    },
    {
      id: "M14-Q2",
      question: "Was ist der 'Expected Loss' in der Konditionenkalkulation?",
      options: [
        "A) Der tatsächliche Verlust bei einer Kundeninsolvenz",
        "B) Die statistisch erwartete Verlusthöhe aus Kreditausfällen, die als Risikokosten in die Kondition eingepreist wird",
        "C) Der Verlust aus Zinsänderungsrisiken bei Festzinskrediten",
        "D) Die Abschreibung auf notleidende Kredite laut HGB",
      ],
      correctIndex: 1,
      explanation: "Expected Loss = Probability of Default (PD) × Loss Given Default (LGD) × Exposure at Default (EAD). Er beschreibt den statistisch erwarteten Verlust und muss in der Kreditkondition als Risikoprämie abgedeckt sein. Ist er nicht gedeckt, wird das Kreditgeschäft risikogerechte Renditen unterschreiten.",
    },
    {
      id: "M14-Q3",
      question: "Ein Firmenkundenberater führt ein Konditionengespräch. Was empfiehlt Modul M14 als ersten Schritt, bevor über Preise gesprochen wird?",
      options: [
        "A) Das Konkurrenzangebot des Kunden einzuholen",
        "B) Den Nutzen der Bankbeziehung und des Produkts klar kommunizieren",
        "C) Die eigene Mindestkondition zu nennen und dann zu verhandeln",
        "D) Den Kunden auf § 18 KWG hinzuweisen",
      ],
      correctIndex: 1,
      explanation: "Wertbasiertes Konditionengespräch bedeutet: Erst den Wert kommunizieren (Zuverlässigkeit, Schnelligkeit, Expertise, Verbundleistungen), dann über den Preis sprechen. Wer zuerst über Konditionen spricht, macht sich zum Commodity. Wer zuerst Nutzen kommuniziert, rechtfertigt sein Pricing.",
    },
    {
      id: "M14-Q4",
      question: "Welche vier Ertragskomponenten bilden den Kundendeckungsbeitrag im Firmenkundengeschäft?",
      options: [
        "A) Zinsmarge, Provisionsmarge, Risikokosten, Betriebskosten",
        "B) Kreditzins, Kontoführungsgebühr, Beratungshonorar, Verbundprovisionen",
        "C) Zinsergebnis, Provisionsergebnis, Bewertungsergebnis, Overheadkosten",
        "D) Bruttomarge, Handelsspanne, Refinanzierungskosten, Eigenkapitalkosten",
      ],
      correctIndex: 0,
      explanation: "Der Kundendeckungsbeitrag setzt sich zusammen aus: Zinsmarge (Kreditzins minus Refinanzierungskosten), Provisionsmarge (Gebühren, Verbundprovisionen), abzüglich Risikokosten (Expected Loss) und Betriebskosten (Zeit- und Sachaufwand für den Kunden). Das Ergebnis zeigt die echte Profitabilität.",
    },
    {
      id: "M14-Q5",
      question: "Welchen der folgenden Kunden sollte ein Berater laut der Ertragslogik von M14 am intensivsten betreuen?",
      options: [
        "A) Den Kunden mit dem höchsten Kreditvolumen",
        "B) Den Kunden mit dem höchsten Deckungsbeitrag",
        "C) Den Kunden mit der längsten Bankverbindung",
        "D) Den Kunden mit dem besten Rating",
      ],
      correctIndex: 1,
      explanation: "Die Betreuungsintensität sollte am Deckungsbeitrag ausgerichtet werden — nicht am Kreditvolumen oder der Dauer der Bankverbindung. Hohe Kreditvolumina mit geringer Marge liefern weniger Deckungsbeitrag als kleinere Kunden mit breitem Produktmix und Verbundgeschäft.",
    },
  ],

  "M15": [
    {
      id: "M15-Q1",
      question: "Was ist der erste Schritt bei der Entwicklung einer Marktbearbeitungsstrategie laut Modul M15?",
      options: [
        "A) Die eigene NMZ im Bestand analysieren",
        "B) Das Marktpotenzial im Zielsegment analysieren und adressierbare Neukunden-Opportunitäten schätzen",
        "C) Das jährliche Vertriebsbudget festlegen",
        "D) Die Verbundpartner über das neue Segment informieren",
      ],
      correctIndex: 1,
      explanation: "Der erste Schritt ist die Marktpotenzialanalyse: Wie viele potenzielle Neukunden gibt es im Zielsegment? Wie viele werden bereits von der eigenen Bank betreut? Was ist das adressierbare Volumen? Ohne diese Grundlage fehlt die Basis für eine fundierte Strategie.",
    },
    {
      id: "M15-Q2",
      question: "Was ist ein 'Wertversprechen' (Value Proposition) im Kontext der Marktbearbeitungsstrategie?",
      options: [
        "A) Der zugesicherte Zinssatz für Neukunden",
        "B) Die spezifische Antwort auf die Frage: 'Warum sollte dieser Kunde zu unserer Bank kommen und nicht zum Wettbewerb?'",
        "C) Die gesetzlich vorgeschriebene Beratungsdokumentation nach MiFID II",
        "D) Das jährliche Ertragsziel für das Segment",
      ],
      correctIndex: 1,
      explanation: "Das Wertversprechen beschreibt den spezifischen Mehrwert, den die eigene Bank im Zielsegment bietet — z. B. Branchenexpertise, regionale Präsenz, Verbundlösungen, Entscheidungsschnelligkeit. Es beantwortet die Frage, die jeder potenzielle Neukunde implizit stellt: Warum gerade ihr?",
    },
    {
      id: "M15-Q3",
      question: "Welches Instrument dient laut Modul M15 dazu, die Wettbewerbsposition der eigenen Bank im Zielsegment zu bewerten?",
      options: [
        "A) Nur die eigene NMZ im Vergleich zum Branchendurchschnitt",
        "B) Analyse von Stärken, Schwächen und Differenzierungspotenzialen gegenüber dem Wettbewerb",
        "C) Das BVR-Benchmark-Reporting",
        "D) Der Net Promoter Score (NPS) der eigenen Kunden",
      ],
      correctIndex: 1,
      explanation: "Die Wettbewerbspositionierung erfolgt durch eine ehrliche Stärken-Schwächen-Analyse im Zielsegment: Wo sind wir besser als der Wettbewerb? Wo haben wir Nachholbedarf? Was sind unsere echten Differenzierungspotenziale? Erst dann kann ein glaubwürdiges Wertversprechen entwickelt werden.",
    },
    {
      id: "M15-Q4",
      question: "Warum ist die Neukundenansprache über Empfehlungen (Multiplikatoren) oft effektiver als Kaltakquise?",
      options: [
        "A) Weil Kaltakquise gesetzlich verboten ist",
        "B) Weil Empfehlungen eine vertrauensbildende Vorleistung liefern, die den Erstkontakt erheblich erleichtert",
        "C) Weil Multiplikatoren immer eine Provision verlangen und daher leistungsfähiger sind",
        "D) Weil agree nur Empfehlungskontakte verarbeiten kann",
      ],
      correctIndex: 1,
      explanation: "Empfehlungen von Steuerberatern, Rechtsanwälten oder anderen vertrauenswürdigen Multiplikatoren liefern eine Vertrauensvorleistung: Der potenzielle Neukunde kommt nicht als Fremder, sondern mit einer Empfehlung, die Skepsis abbaut. Das erhöht die Conversion-Rate erheblich gegenüber Kaltakquise.",
    },
    {
      id: "M15-Q5",
      question: "Was enthält ein strukturierter Jahresplan nach Modul M15?",
      options: [
        "A) Nur Ertragsziele für das Segment",
        "B) Zielgrößen, konkrete Maßnahmen und Meilensteine über das Jahr verteilt",
        "C) Die Kreditvolumina aller Neukunden im Vorjahr",
        "D) Die Zinsprognose der EZB für das laufende Jahr",
      ],
      correctIndex: 1,
      explanation: "Ein strukturierter Jahresplan kombiniert messbare Zielgrößen (Anzahl Erstkontakte, Neukunden, Ertrag) mit konkreten Maßnahmen (Events, Netzwerktreffen, Verbundpartner-Aktionen) und zeitlichen Meilensteinen. Nur die Kombination aller drei Elemente macht den Plan steuerbar.",
    },
  ],

  "M16": [
    {
      id: "M16-Q1",
      question: "Was misst die Nettomargenziffer (NMZ) im VR-Firmenkundensegment?",
      options: [
        "A) Den absoluten Deckungsbeitrag in EUR pro Kunde",
        "B) Die bereinigte Ertragsmarge auf das betreute Kreditvolumen — in Basispunkten oder Prozent",
        "C) Die Anzahl der Cross-Selling-Produkte pro Kunde",
        "D) Den Risikogewichteten Aktivawert (RWA) des Bestands",
      ],
      correctIndex: 1,
      explanation: "Die NMZ ist die zentrale relative Steuerungsgröße: Sie misst, wie viel Nettoertrag (nach Risikokosten, Refinanzierung, anteiligen Betriebskosten) je Einheit betreutes Volumen generiert wird. Sie erlaubt den Vergleich von Kunden unterschiedlicher Größe auf einer gemeinsamen Skala.",
    },
    {
      id: "M16-Q2",
      question: "Welche Maßnahme hat den größten direkten Hebel auf die NMZ eines einzelnen Kunden?",
      options: [
        "A) Das Kreditvolumen erhöhen",
        "B) Zusätzliche Verbundprodukte platzieren und die Konditionsbasis risikogerecht anpassen",
        "C) Die Besuchsfrequenz erhöhen",
        "D) Den Kunden in eine höhere Kundensegmentklasse einstufen",
      ],
      correctIndex: 1,
      explanation: "NMZ-Verbesserungen entstehen primär durch zwei Hebel: Konditionsanpassung (höhere Zinsmarge bei risikogerechtem Pricing) und Provisionserträge durch Verbundprodukte. Höheres Kreditvolumen allein verbessert die NMZ nicht, wenn die Marge konstant bleibt — es erhöht nur den absoluten Ertrag.",
    },
    {
      id: "M16-Q3",
      question: "Wozu dient der NMZ-Bestandsbericht in agree?",
      options: [
        "A) Um die Bonität aller Kunden in einer Übersicht zu sehen",
        "B) Um Kunden nach NMZ zu sortieren und Verbesserungspotenziale im Bestand zu identifizieren",
        "C) Um die Frühwarnindikatoren aller Kreditnehmer zu überwachen",
        "D) Um die Jahresabschlüsse aller Kunden automatisch zu verarbeiten",
      ],
      correctIndex: 1,
      explanation: "Der NMZ-Bestandsbericht in agree listet alle Kunden nach ihrer Nettomargenziffer und ermöglicht es dem Berater, auf einen Blick die ertragsschwächsten Kunden zu identifizieren, bei denen konkrete Maßnahmen zur NMZ-Verbesserung ansetzen sollten.",
    },
    {
      id: "M16-Q4",
      question: "Was ist das 'dominante Schwachfeld' in der NMZ-Analyse eines Bestands?",
      options: [
        "A) Der Kunde mit dem niedrigsten Rating",
        "B) Die Ertragskomponente (Zins, Provision, Risiko), die am meisten zur niedrigen NMZ beiträgt",
        "C) Das Produkt mit den meisten Reklamationen",
        "D) Der Bereich mit der höchsten Mitarbeiterfluktuation",
      ],
      correctIndex: 1,
      explanation: "Das dominante Schwachfeld ist die Ertragskomponente, die systematisch die NMZ drückt — z. B. zu niedrige Kreditmargen (Zins), fehlende Verbundprodukte (Provision) oder zu hohe Risikokosten (schlechte Portfolioqualität). Die Identifikation ermöglicht gezielte Steuerung statt Gießkannenprinzip.",
    },
    {
      id: "M16-Q5",
      question: "Warum ist die NMZ besser als der absolute Deckungsbeitrag zur Steuerung der Betreuungsintensität?",
      options: [
        "A) Weil die NMZ in agree automatisch berechnet wird, der DB nicht",
        "B) Weil die NMZ Kunden unterschiedlicher Größe vergleichbar macht — ein kleiner Kunde mit hoher NMZ kann rentabler sein als ein großer mit niedriger NMZ",
        "C) Weil der DB nach HGB berechnet wird und steuerlich nicht relevant ist",
        "D) Weil die NMZ dem Kunden kommuniziert werden darf, der DB nicht",
      ],
      correctIndex: 1,
      explanation: "Die NMZ normiert auf das Volumen und macht damit Äpfel mit Birnen vergleichbar. Ein Kunde mit 500.000 EUR Kredit und hoher NMZ kann rentabler sein als ein Kunde mit 5 Mio. EUR und geringer NMZ. Absolute DBs bevorzugen systematisch große Kunden — unabhängig von deren Effizienz.",
    },
  ],

  "M17": [
    {
      id: "M17-Q1",
      question: "Welche fünf Funktionsbereiche von agree sind für Firmenkundenberater besonders relevant?",
      options: [
        "A) Buchführung, Lohnabrechnung, SCHUFA, Depot, Kartenverwaltung",
        "B) Kundenstamm/CRM, Kreditanalyse, Gesprächsdokumentation (UnternehmerDialog), NMZ-Reporting, Frühwarnung",
        "C) Online-Banking, Mobile App, Video-Beratung, Chatbot, Dokumentenarchiv",
        "D) Budgetplanung, HR-Management, Compliance, Risikocontrolling, Buchhaltung",
      ],
      correctIndex: 1,
      explanation: "Die fünf zentralen agree-Funktionsbereiche für FKB sind: Kundenstamm und CRM-Daten, Kreditanalyse und Rating, Gesprächsdokumentation über den UnternehmerDialog, NMZ-Bestandsreporting und Frühwarnberichte. Diese Bereiche decken den Kernalltag des Firmenkundenberaters ab.",
    },
    {
      id: "M17-Q2",
      question: "Was ist das Ziel der digitalen Gesprächsvorbereitung in agree vor einem Jahresgespräch?",
      options: [
        "A) Alle Dokumente des Kunden auszudrucken",
        "B) Relevante Kundendaten, NMZ, letzte Aktivitäten und offene Folgeaufgaben vor dem Termin strukturiert zu sichten",
        "C) Das Kreditrating des Kunden zu aktualisieren",
        "D) Den Kunden per E-Mail über die Tagesordnung zu informieren",
      ],
      correctIndex: 1,
      explanation: "Die digitale Vorbereitung in agree erlaubt dem Berater, in wenigen Minuten NMZ, Portf oliozusammensetzung, letzte Gesprächsnotizen, offene Aufgaben und Auffälligkeiten zu sichten — so kommt er gut vorbereitet und kann sich im Gespräch auf Inhalte konzentrieren statt auf Datenbeschaffung.",
    },
    {
      id: "M17-Q3",
      question: "Wie hilft der UnternehmerDialog in agree bei der Bedarfserfassung?",
      options: [
        "A) Er erstellt automatisch Kreditanträge aus dem Gespräch",
        "B) Er liefert einen strukturierten Leitfaden, der alle Bedarfsdimensionen führt, und ermöglicht unmittelbare Dokumentation von Bedarfen und Folgeaktivitäten",
        "C) Er sendet automatisch Angebote an den Kunden nach dem Gespräch",
        "D) Er berechnet den Expected Loss auf Basis der Gesprächsnotizen",
      ],
      correctIndex: 1,
      explanation: "Der UnternehmerDialog in agree ist ein digitaler Gesprächsstrukturierer: Er führt den Berater durch alle relevanten Dimensionen (Unternehmen, Finanzierung, Absicherung, Vorsorge, Zukunft) und erlaubt die direkte Dokumentation von Bedarfen und Folgeaufgaben — ohne Doppelerfassung nach dem Gespräch.",
    },
    {
      id: "M17-Q4",
      question: "Was zeigt der Frühwarnbericht in agree?",
      options: [
        "A) Kunden, die einen Kredit anfragen möchten",
        "B) Kunden, bei denen Frühwarnsignale (z. B. Kontokorrent-Überziehung, Rücklastschriften, Rating-Verschlechterung) ausgelöst wurden",
        "C) Kunden mit überfälligen Jahresabschlüssen",
        "D) Kunden, bei denen das Gespräch länger als 6 Monate zurückliegt",
      ],
      correctIndex: 1,
      explanation: "Der Frühwarnbericht aggregiert automatisiert Signale aus Kontobewegungen, Rating-Veränderungen und Jahresabschluss-Fälligkeiten. Er hilft dem Berater, risikorelevante Kunden frühzeitig zu identifizieren — entsprechend dem Ziel, 80 % der Insolvenzen 12–18 Monate vor Eintreten zu erkennen.",
    },
    {
      id: "M17-Q5",
      question: "Wie identifiziert ein Berater laut Modul M17 seine persönlichen 'Zeitfresser' im agree-Workflow?",
      options: [
        "A) Durch Analyse seines Kalenders und der Meetingdauer",
        "B) Durch Analyse der eigenen Nutzungsgewohnheiten: Welche Aufgaben dauern länger als nötig? Welche agree-Funktion reduziert diesen Aufwand?",
        "C) Durch Befragung des Vorgesetzten zur eigenen Produktivität",
        "D) Durch Vergleich der eigenen Gesprächsanzahl mit dem Teamdurchschnitt",
      ],
      correctIndex: 1,
      explanation: "Zeitfresser-Analyse bedeutet: Wo verbringt der Berater unverhältnismäßig viel Zeit für Routineaufgaben (Dokumentation, Datenbeschaffung, Nachtelefonieren)? Dann prüft er, welche agree-Funktion diese Aufgabe automatisiert oder vereinfacht. Das ist der Kern des Moduls: Systemkompetenz als Zeitgewinn.",
    },
  ],

  "M18": [
    {
      id: "M18-Q1",
      question: "Was ist der Kernunterschied zwischen reaktivem und trigger-basiertem Vertrieb?",
      options: [
        "A) Reaktiver Vertrieb ist digital, trigger-basierter analog",
        "B) Reaktiver Vertrieb wartet auf Kundenanfragen; trigger-basierter Vertrieb nutzt Datensignale, um proaktiv zum richtigen Zeitpunkt zu kontaktieren",
        "C) Trigger-basierter Vertrieb ist teurer und nur für Großkunden geeignet",
        "D) Reaktiver Vertrieb ist nach MaRisk nicht erlaubt",
      ],
      correctIndex: 1,
      explanation: "Trigger-basierter Vertrieb nutzt Ereignisse in den Kundendaten als Auslöser für proaktive Kontaktaufnahme — z. B. eine hohe Kontokorrent-Inanspruchnahme als Signal für Finanzierungsbedarf. Reaktiver Vertrieb wartet, bis der Kunde kommt. Trigger-basiert ist schneller und relevanter.",
    },
    {
      id: "M18-Q2",
      question: "Welches der folgenden Ereignisse in agree-Daten ist ein typisches Trigger-Signal für einen potenziellen Investitionskredit-Bedarf?",
      options: [
        "A) Der Kunde hat seit 3 Monaten kein Girokonto-Umsatz",
        "B) Regelmäßige Kontokorrent-Inanspruchnahme nahe des Limits über mehrere Monate",
        "C) Der Jahresabschluss liegt 6 Monate vor Fälligkeit",
        "D) Der Kunde hat ein Gehaltskonto bei der Bank",
      ],
      correctIndex: 1,
      explanation: "Dauerhaft ausgeschöpfter Kontokorrent signalisiert strukturellen Liquiditätsbedarf — oft ein Zeichen für nicht finanzierte Investitionen oder Working-Capital-Lücken. Das ist ein klassisches Trigger-Signal: Der Berater kann proaktiv ein Investitionsgespräch initiieren, bevor der Kunde selbst aktiv wird.",
    },
    {
      id: "M18-Q3",
      question: "Welche DSGVO-Grundsätze gelten bei der Nutzung von Kundendaten für den trigger-basierten Vertrieb?",
      options: [
        "A) Kundendaten dürfen für den Vertrieb frei verwendet werden, solange der Kunde ein Girokonto hat",
        "B) Daten dürfen nur für den vereinbarten Zweck genutzt werden; der Kunde muss informiert werden, und es gelten Zweckbindung und Datensparsamkeit",
        "C) Trigger-Daten sind anonymisiert und unterliegen nicht der DSGVO",
        "D) Interne Systemdaten aus agree unterliegen nicht der DSGVO, nur externe Daten",
      ],
      correctIndex: 1,
      explanation: "Die DSGVO gilt auch für interne Kundendaten: Zweckbindung (Daten nur für vereinbarte Zwecke nutzen), Informationspflicht (Kunden müssen wissen, wie ihre Daten genutzt werden) und Datensparsamkeit. Im Firmenkundengeschäft ist die Nutzung transaktionaler Daten für Beratungszwecke grundsätzlich zulässig, aber transparent zu gestalten.",
    },
    {
      id: "M18-Q4",
      question: "Welcher Trigger-Typ hat die längste Vorlaufzeit für proaktive Vertriebsmaßnahmen?",
      options: [
        "A) Reaktive Trigger (Kundenkontakt nach Reklamation)",
        "B) Verhaltens-Trigger (aktuelle Kontokorrentnutzung)",
        "C) Lebenszyklus-Trigger (Unternehmensgründung, Investitionszyklen, Altersentwicklung des Inhabers)",
        "D) Markt-Trigger (Zinsveränderung der EZB gestern)",
      ],
      correctIndex: 2,
      explanation: "Lebenszyklus-Trigger wie Unternehmensalter, Inhaberalter oder bekannte Investitionszyklen haben die längste Vorlaufzeit — manchmal Jahre. Sie erlauben die frühzeitigste Positionierung. Verhaltens-Trigger und Markt-Trigger sind kurzfristiger und erfordern schnelleres Handeln.",
    },
    {
      id: "M18-Q5",
      question: "Warum ist Datenqualität im CRM-Bestand eine Voraussetzung für effektiven trigger-basierten Vertrieb?",
      options: [
        "A) Weil schlechte Daten zu BaFin-Sanktionen führen",
        "B) Weil Trigger-Signale nur dann relevant sind, wenn die zugrundeliegenden Kundendaten aktuell und vollständig sind — falsche Branche, veraltetes Inhaberalter, fehlende Umsatzdaten führen zu falschen Signalen",
        "C) Weil agree ohne vollständige Daten nicht starten kann",
        "D) Weil die DSGVO vollständige Kundendaten vorschreibt",
      ],
      correctIndex: 1,
      explanation: "Trigger-Algorithmen sind nur so gut wie die Daten, auf denen sie basieren. Ist die Branche falsch erfasst, das Inhaberalter veraltet oder Umsatzdaten lückenhaft, erzeugt das System irrelevante oder falsche Trigger. Datenqualitätspflege ist daher keine Verwaltungsaufgabe, sondern vertriebliche Voraussetzung.",
    },
  ],

  "M19": [
    {
      id: "M19-Q1",
      question: "Was ist der Unterschied zwischen explizitem und implizitem Wissen im Kontext des Wissenstransfers?",
      options: [
        "A) Explizites Wissen ist geheim, implizites öffentlich",
        "B) Explizites Wissen ist dokumentiert und übertragbar; implizites Wissen ist an Erfahrung gebunden und schwer zu verbalisieren",
        "C) Implizites Wissen ist veraltet, explizites Wissen ist aktuell",
        "D) Explizites Wissen betrifft Produkte, implizites Wissen betrifft Kunden",
      ],
      correctIndex: 1,
      explanation: "Explizites Wissen (Handbücher, Prozesse, Checklisten) ist leicht dokumentierbar und übertragbar. Implizites Wissen (Intuition, Erfahrung, 'Fingerspitzengefühl') ist an die Person gebunden und erfordert besondere Transfermethoden wie Mentoring, Shadowing oder strukturierte Fallbesprechungen.",
    },
    {
      id: "M19-Q2",
      question: "Welche der folgenden Methoden ist besonders geeignet, implizites Expertenwissen von erfahrenen Beratern auf Nachwuchskräfte zu übertragen?",
      options: [
        "A) Schriftliches Handbuch mit Best-Practice-Beispielen",
        "B) E-Learning-Modul mit Multiple-Choice-Tests",
        "C) Shadowing und Tandem-Lernen — gemeinsame Kundengespräche mit anschließender Reflexion",
        "D) Videokonferenz mit Wissenspräsentation",
      ],
      correctIndex: 2,
      explanation: "Implizites Wissen wird am effektivsten durch direkte Erfahrungsübertragung transferiert: Shadowing (Beobachten im realen Kontext) und Tandem-Lernen (gemeinsam handeln, dann reflektieren) machen unbewusstes Können sichtbar und nachvollziehbar. Schriftliche Formate greifen hier zu kurz.",
    },
    {
      id: "M19-Q3",
      question: "Was ist eine 'Community of Practice' im Firmenkundenteam?",
      options: [
        "A) Ein formelles Ausschussgremium der Bank",
        "B) Eine selbstorganisierte Lerngemeinschaft von Beratern, die durch gemeinsame Praxis, Fälle und Reflexion kollektiv Expertise aufbauen",
        "C) Eine externe Beratungsgruppe für Kunden",
        "D) Ein Pflichtprogramm der Personalentwicklung",
      ],
      correctIndex: 1,
      explanation: "Communities of Practice (Wenger, 1998) sind informelle Gruppen, die durch geteilte Praxis und gemeinsames Lernen Expertise entwickeln. Im FK-Team bedeutet das: regelmäßige Fallbesprechungen, kollegiale Beratung, Wissensteilung — ohne formalen Schulungscharakter.",
    },
    {
      id: "M19-Q4",
      question: "Was sind typische Transferbarrieren für Wissenstransfer in einem Firmenkundenteam?",
      options: [
        "A) Zu hohe Fachkompetenz der Mitarbeiter",
        "B) Zeitdruck, fehlende Strukturen für den Austausch, mangelnde psychologische Sicherheit und das Gefühl, Wissen = Machtposition",
        "C) Zu viele Schulungsangebote, die ablenken",
        "D) Zu gute IT-Systeme, die Wissen automatisch speichern",
      ],
      correctIndex: 1,
      explanation: "Die häufigsten Transferbarrieren sind: Zeitdruck (kein Raum für Austausch), fehlende Strukturen (kein regelmäßiges Format), mangelnde Sicherheit (Angst, Fehler zu zeigen) und Wissenshoarding (implizites Motiv: 'Wenn ich mein Wissen teile, verliere ich meinen Expertenstatus'). Alle vier müssen adressiert werden.",
    },
    {
      id: "M19-Q5",
      question: "Das SECI-Modell von Nonaka & Takeuchi beschreibt vier Wissenswandlungsprozesse. Welcher Prozess findet statt, wenn ein Berater seine intuitive Kundenstrategie in eine Checkliste schreibt?",
      options: [
        "A) Sozialisation (implizit → implizit)",
        "B) Externalisierung (implizit → explizit)",
        "C) Kombination (explizit → explizit)",
        "D) Internalisierung (explizit → implizit)",
      ],
      correctIndex: 1,
      explanation: "Externalisierung bezeichnet den Prozess, bei dem implizites Wissen (Intuition, Erfahrung) in explizite Form (Checkliste, Modell, Dokumentation) überführt wird. Das ist der wertvollste, aber schwierigste Transferschritt — er macht persönliche Expertise für andere nutzbar.",
    },
  ],

  "M20": [
    {
      id: "M20-Q1",
      question: "Was beschreibt Mark Granovetters Konzept der 'Strength of Weak Ties'?",
      options: [
        "A) Starke Beziehungen sind für Neukundenakquise am wichtigsten",
        "B) Schwache Kontakte erschließen andere Informationskreise und Netzwerke, die starke Kontakte nicht erreichen",
        "C) Netzwerken ist nur für extrovertierte Berater sinnvoll",
        "D) Digitale Netzwerke sind stärker als persönliche Kontakte",
      ],
      correctIndex: 1,
      explanation: "Granovetters (1973) Kernthese: Starke Bindungen bewegen sich in denselben sozialen Kreisen — man kennt bereits dieselben Menschen. Schwache Bindungen dagegen bauen Brücken zu anderen Netzwerken und liefern neue, nicht-redundante Informationen und Kontakte. Für Neukundenakquise sind schwache Ties daher oft wertvoller.",
    },
    {
      id: "M20-Q2",
      question: "Was ist eine 'Sichtbarkeitsstrategie' für einen Firmenkundenberater?",
      options: [
        "A) Ein Plan zur Erhöhung der Anzahl der Kundenbesuche",
        "B) Ein systematischer Ansatz, durch Fachvorträge, Publikationen und Netzwerkpräsenz als Experte wahrgenommen zu werden",
        "C) Die Strategie, möglichst viele LinkedIn-Kontakte zu sammeln",
        "D) Ein Marketingplan der Bankzentrale für das Firmenkundensegment",
      ],
      correctIndex: 1,
      explanation: "Eine persönliche Sichtbarkeitsstrategie positioniert den Berater als Fachexperten im Zielsegment — durch Fachvorträge bei IHK oder Verbänden, Gastbeiträge in regionalen Medien, aktive Social-Media-Präsenz und Netzwerkengagement. Sichtbarkeit schafft Vertrauen vor dem ersten Kontakt.",
    },
    {
      id: "M20-Q3",
      question: "Ronald Burts Konzept der 'Structural Holes' beschreibt, welche Netzwerkposition strategisch am wertvollsten ist?",
      options: [
        "A) Derjenige mit den meisten direkten Kontakten",
        "B) Derjenige, der als einziger Verbindung zwischen unverbundenen Gruppen herstellt (Broker-Position)",
        "C) Derjenige, der in einer eng vernetzten Clique ist",
        "D) Derjenige mit den stärksten Bindungen zu Entscheidungsträgern",
      ],
      correctIndex: 1,
      explanation: "Burt (1992) zeigt: Wer als Broker zwischen ansonsten unverbundenen Gruppen vermittelt ('Structural Hole überbrücken'), kontrolliert den Informationsfluss und erlangt strategische Vorteile. Ein FK-Berater, der Unternehmer mit Steuerberatern, Investoren und Branchenverbänden vernetzt, besetzt genau diese wertvolle Broker-Position.",
    },
    {
      id: "M20-Q4",
      question: "Welche drei Netzwerkdimensionen sollte ein Firmenkundenberater systematisch entwickeln?",
      options: [
        "A) Lokales, regionales und nationales Netzwerk",
        "B) Kundennetzwerk, Multiplikatorennetzwerk und internes Kompetenznetzwerk",
        "C) Digitales, analoges und internationales Netzwerk",
        "D) Kreditnetzwerk, Einlagennetzwerk und Verbundnetzwerk",
      ],
      correctIndex: 1,
      explanation: "Die drei Netzwerkdimensionen sind: Kundennetzwerk (direkte Kundenbeziehungen pflegen), Multiplikatorennetzwerk (Steuerberater, Rechtsanwälte, Unternehmensberater als Empfehlungsgeber) und internes Kompetenznetzwerk (Spezialisten der eigenen Bank und Verbundpartner). Alle drei Dimensionen ergänzen sich.",
    },
    {
      id: "M20-Q5",
      question: "Welches Prinzip sollte die Netzwerkpflege eines Firmenkundenberaters laut Modul M20 leiten?",
      options: [
        "A) Möglichst viele Kontakte sammeln — Quantität vor Qualität",
        "B) 'Geben vor Nehmen' — regelmäßig Mehrwert liefern ohne unmittelbare Gegenleistungserwartung",
        "C) Netzwerkpflege ausschließlich auf digitalen Plattformen durchführen",
        "D) Nur Kontakte pflegen, von denen direkter Geschäftsabschluss erwartet wird",
      ],
      correctIndex: 1,
      explanation: "Nachhaltige Netzwerkbeziehungen basieren auf Reziprozität und Vertrauen. Wer regelmäßig relevante Informationen teilt, hilft und Mehrwert liefert — ohne sofortige Gegenleistungserwartung — baut langfristige Beziehungskapital auf. Transaktionale Netzwerkpflege ('was bringt mir das?') bleibt oberflächlich.",
    },
  ],

  "M21": [
    {
      id: "M21-Q1",
      question: "Das 8-Felder-Framework für Kreditentscheidungen dient welchem regulatorischen Ziel?",
      options: [
        "A) Der Umsetzung von Basel III-Kapitalanforderungen",
        "B) Der MaRisk BTO 1.1-konformen Dokumentation strukturierter Kreditanalysen",
        "C) Der Erfüllung der IFRS 9-Rückstellungspflichten",
        "D) Der Einhaltung der BaFin-Großkreditgrenze",
      ],
      correctIndex: 1,
      explanation: "Das 8-Felder-Framework macht Kreditentscheidungen transparent, nachvollziehbar und prüfsicher nach MaRisk BTO 1.1 (BaFin, 2023). Es stellt sicher, dass alle wesentlichen Risikofelder strukturiert analysiert und dokumentiert werden — eine Grundanforderung für die Kreditvergabe.",
    },
    {
      id: "M21-Q2",
      question: "Was ist laut Becker (2019) das wichtigste Trennungsprinzip in der Kreditanalyse?",
      options: [
        "A) Trennung von kurz- und langfristigen Verbindlichkeiten",
        "B) Trennung von Rückzahlungsfähigkeit (primär) und Sicherheitenqualität (sekundär)",
        "C) Trennung von quantitativen und qualitativen Faktoren in zwei separate Gutachten",
        "D) Trennung von Kreditnehmer- und Bürgschaftsbonitäten",
      ],
      correctIndex: 1,
      explanation: "Becker (2019) betont: Eine vollständige Kreditanalyse trennt strikt die Rückzahlungsfähigkeit (primäre Rückzahlungsquelle: operativer Cashflow) von der Sicherheitenqualität (sekundäre Rückzahlungsquelle). Gute Sicherheiten ersetzen keine fehlende Rückzahlungsfähigkeit.",
    },
    {
      id: "M21-Q3",
      question: "Ein Unternehmen hat folgende Daten: EBIT 300.000 EUR, Zinsaufwand 80.000 EUR, Tilgung 120.000 EUR. Wie hoch ist der DSCR (Debt Service Coverage Ratio), und was bedeutet das?",
      options: [
        "A) DSCR = 1,5 – ausreichende Deckung des Kapitaldienstes",
        "B) DSCR = 3,75 – sehr komfortable Deckung",
        "C) DSCR = 0,75 – Kapitaldienst nicht gedeckt",
        "D) DSCR = 2,5 – gute Deckung",
      ],
      correctIndex: 0,
      explanation: "DSCR = EBIT / (Zins + Tilgung) = 300.000 / (80.000 + 120.000) = 300.000 / 200.000 = 1,5. Ein DSCR von 1,5 bedeutet: Das operative Ergebnis übersteigt den Kapitaldienst um 50 % — ein solider Wert. Unter 1,2 wäre ein Warnsignal, unter 1,0 bedeutete es, dass der Cashflow den Kapitaldienst nicht deckt.",
    },
    {
      id: "M21-Q4",
      question: "Was sind Financial Covenants und welchem Zweck dienen sie im Kreditvertrag?",
      options: [
        "A) Zinsbindungsklauseln, die den Zinssatz für die gesamte Laufzeit fixieren",
        "B) Vertragliche Kennzahlengrenzen, die der Bank bei Verletzung Sonderkündigungsrechte oder Nachbesicherungsansprüche geben — als Frühwarnsystem",
        "C) Garantien des Kreditnehmers für die Beschäftigtenanzahl",
        "D) Gesetzlich vorgeschriebene Klauseln nach § 18 KWG",
      ],
      correctIndex: 1,
      explanation: "Financial Covenants — z. B. Mindest-Eigenkapitalquote, maximaler Verschuldungsgrad, Mindest-DSCR — sind vertragliche Kennzahlengrenzen. Werden sie unterschritten, erhält die Bank Sonderkündigungs- oder Nachbesicherungsrechte. Sie wirken als Frühwarnsystem und ermöglichen proaktives Eingreifen vor einem formellen Kreditausfall.",
    },
    {
      id: "M21-Q5",
      question: "Feld 4 des 8-Felder-Frameworks analysiert die 'Managementqualität'. Welche Informationsquellen sind hierfür primär relevant?",
      options: [
        "A) Jahresabschluss und GuV der letzten 3 Jahre",
        "B) Gespräch mit der Geschäftsführung, Lebenslauf und Track-Record",
        "C) Kreditauskunft und SCHUFA-Score des Geschäftsführers",
        "D) Branchenberichte und Wettbewerbsanalysen",
      ],
      correctIndex: 1,
      explanation: "Managementqualität lässt sich nicht aus Bilanzen ablesen — sie wird im persönlichen Gespräch, durch Analyse des Track-Records (bisherige Entscheidungen, Unternehmensentwicklung) und über den Lebenslauf bewertet. Das ist ein klassischer qualitativer Faktor, der nur durch direkten Kontakt zugänglich ist.",
    },
  ],
  "M22": [
    {
      id: "M22-Q1",
      question: "Welche der fünf Wettbewerbskräfte nach Porter (1979) beschreibt die Gefahr, dass wenige Großabnehmer Preisdruck auf den Lieferanten ausüben?",
      options: [
        "A) Bedrohung durch neue Marktteilnehmer",
        "B) Verhandlungsmacht der Lieferanten",
        "C) Verhandlungsmacht der Kunden",
        "D) Rivalität unter bestehenden Wettbewerbern",
      ],
      correctIndex: 2,
      explanation: "Die Verhandlungsmacht der Kunden (Abnehmer) beschreibt den Preisdruck, den starke oder wenige Großabnehmer auf einen Lieferanten ausüben. Im Kreditkontext ist dies eng mit dem Klumpenrisiko verknüpft: Hängt ein Unternehmen von wenigen Großkunden ab, kann es Preise und Konditionen kaum durchsetzen.",
    },
    {
      id: "M22-Q2",
      question: "Ein Maschinenbauer produziert Standardteile zu mittlerem Preis und ist weder der günstigste Anbieter noch verfügt er über eine erkennbare Alleinstellung. Welche strategische Situation beschreibt Porter (1980)?",
      options: [
        "A) Kostenführerschaft",
        "B) Differenzierungsstrategie",
        "C) Nischenstrategie",
        "D) Stuck in the Middle",
      ],
      correctIndex: 3,
      explanation: "„Stuck in the Middle\" beschreibt ein Unternehmen, das sich für keine der generischen Wettbewerbsstrategien entschieden hat — weder Kostenführerschaft noch Differenzierung noch Fokus. Porter (1980) sieht darin eine strategisch riskante Position, weil das Unternehmen weder über den Preis noch über ein Alleinstellungsmerkmal überzeugen kann.",
    },
    {
      id: "M22-Q3",
      question: "Welches Merkmal gehört laut Barney (1991) zu den VRIN-Kriterien für nachhaltige Wettbewerbsvorteile?",
      options: [
        "A) Sichtbar und kommunizierbar",
        "B) Wertvoll, selten, nicht imitierbar, nicht substituierbar",
        "C) Günstig, standardisiert, skalierbar, digital",
        "D) Messbar, bewertbar, übertragbar, veräußerbar",
      ],
      correctIndex: 1,
      explanation: "Die VRIN-Kriterien des Resource-based View (Barney, 1991) lauten: Valuable (wertvoll), Rare (selten), Inimitable (nicht imitierbar) und Non-substitutable (nicht substituierbar). Nur Ressourcen, die alle vier Kriterien erfüllen, begründen einen dauerhaften Wettbewerbsvorteil — ein zentrales Signal für die mittelfristige Kreditwürdigkeit.",
    },
    {
      id: "M22-Q4",
      question: "Im Praxisfall Haller GmbH entfallen 60 % des Umsatzes auf einen einzigen Kunden. Welche kreditrelevante Risikokategorie ist primär betroffen?",
      options: [
        "A) Zinsänderungsrisiko",
        "B) Klumpenrisiko (Konzentrationsrisiko)",
        "C) Währungsrisiko",
        "D) Operationelles Risiko",
      ],
      correctIndex: 1,
      explanation: "Eine Umsatzkonzentration von 60 % auf einen einzigen Kunden ist ein klassisches Klumpenrisiko (Konzentrationsrisiko). Fällt dieser Kunde aus, gerät die gesamte Ertrags- und Kapitaldienstfähigkeit ins Wanken — ein qualitativer Risikofaktor, der über die reine Bilanzanalyse hinausgeht.",
    },
    {
      id: "M22-Q5",
      question: "Was versteht die SWOT-Analyse unter „Bedrohungen\" (Threats) im Kreditkontext?",
      options: [
        "A) Interne Schwächen des Unternehmens",
        "B) Externe Entwicklungen, die das Ertragspotenzial gefährden",
        "C) Risiken aus dem Kreditvertrag",
        "D) Fehlende Sicherheiten",
      ],
      correctIndex: 1,
      explanation: "„Threats\" (Bedrohungen) sind externe Entwicklungen — etwa Marktveränderungen, neue Wettbewerber oder regulatorische Eingriffe —, die das künftige Ertragspotenzial gefährden. Sie sind von den internen Schwächen (Weaknesses) abzugrenzen und im Kreditkontext für die Beurteilung der Zukunftsfähigkeit entscheidend.",
    },
    {
      id: "M22-Q6",
      question: "Welche regulatorische Vorschrift verpflichtet Kreditinstitute, die wirtschaftlichen Verhältnisse eines Kreditnehmers (ab 750.000 EUR) vollständig zu analysieren?",
      options: [
        "A) BelWertV § 4",
        "B) CRR Art. 122",
        "C) § 18 KWG",
        "D) MaRisk BTO 1.2.1",
      ],
      correctIndex: 2,
      explanation: "§ 18 KWG verpflichtet Kreditinstitute, sich bei Krediten ab 750.000 EUR die wirtschaftlichen Verhältnisse des Kreditnehmers offenlegen zu lassen und diese zu analysieren. Die strategische Geschäftsmodellbewertung ist Teil dieser umfassenden Analysepflicht.",
    },
    {
      id: "M22-Q7",
      question: "Ein 63-jähriger Alleingeschäftsführer plant keine Nachfolgeregelung. Wie ist das im Rahmen einer strategischen Kreditbewertung einzuordnen?",
      options: [
        "A) Nicht kreditrelevant, da operativ nicht messbar",
        "B) Schwäche in der SWOT-Analyse und strukturelles Risiko für die Fortführungsfähigkeit",
        "C) Nur relevant bei Krediten über 5 Mio. EUR",
        "D) Relevant, aber ausschließlich durch Sicherheiten zu kompensieren",
      ],
      correctIndex: 1,
      explanation: "Eine fehlende Nachfolgeregelung bei einem alleinigen, älteren Geschäftsführer ist ein „Succession Gap\" — eine Schwäche in der SWOT-Analyse und ein strukturelles Risiko für die Fortführungsfähigkeit. Es ist ein qualitativer, nicht durch Sicherheiten kompensierbarer Faktor, der unabhängig von der Kredithöhe in die Bewertung gehört.",
    },
    {
      id: "M22-Q8",
      question: "Welcher didaktische Ansatz liegt der Fallarbeit in diesem Modul zugrunde, bei dem Lernende an einem authentischen, ungelösten Problem aktiv Wissen konstruieren?",
      options: [
        "A) Instruktionales Design nach Gagné",
        "B) Problembasiertes Lernen nach Barrows (1986)",
        "C) Mastery Learning nach Bloom",
        "D) Situiertes Lernen in authentischen Lernumgebungen",
      ],
      correctIndex: 1,
      explanation: "Problembasiertes Lernen (Barrows, 1986) stellt ein authentisches, ungelöstes Problem an den Anfang des Lernprozesses: Lernende konstruieren Wissen aktiv, indem sie den Fall analysieren und eine Lösung erarbeiten. Genau dieses Prinzip trägt die Fallarbeit am Beispiel der Haller GmbH.",
    },
  ],
};

export function getQuizForModule(moduleId: string): QuizQuestion[] {
  return QUIZZES[moduleId] ?? [];
}
